#ifndef COLORS_H_
#define COLORS_H_

#define HEXA(hex) (((hex) << 8) | 0xFF)

#define COLOR_49ERSRED_R 170
#define COLOR_49ERSRED_G 0
#define COLOR_49ERSRED_B 0
#define COLOR_49ERSRED_HEX COLOR_49ERSRED_R << 16 | COLOR_49ERSRED_G  << 8 | COLOR_49ERSRED_B


#define COLOR_ADMIRAL_R 5
#define COLOR_ADMIRAL_G 16
#define COLOR_ADMIRAL_B 148
#define COLOR_ADMIRAL_HEX COLOR_ADMIRAL_R << 16 | COLOR_ADMIRAL_G  << 8 | COLOR_ADMIRAL_B


#define COLOR_AEGEAN_R 31
#define COLOR_AEGEAN_G 69
#define COLOR_AEGEAN_B 110
#define COLOR_AEGEAN_HEX COLOR_AEGEAN_R << 16 | COLOR_AEGEAN_G  << 8 | COLOR_AEGEAN_B


#define COLOR_AFFAIR_R 111
#define COLOR_AFFAIR_G 70
#define COLOR_AFFAIR_B 133
#define COLOR_AFFAIR_HEX COLOR_AFFAIR_R << 16 | COLOR_AFFAIR_G  << 8 | COLOR_AFFAIR_B


#define COLOR_AIRSUPERIORITYBLUE_R 114
#define COLOR_AIRSUPERIORITYBLUE_G 160
#define COLOR_AIRSUPERIORITYBLUE_B 193
#define COLOR_AIRSUPERIORITYBLUE_HEX COLOR_AIRSUPERIORITYBLUE_R << 16 | COLOR_AIRSUPERIORITYBLUE_G  << 8 | COLOR_AIRSUPERIORITYBLUE_B


#define COLOR_AJAXRED_R 210
#define COLOR_AJAXRED_G 18
#define COLOR_AJAXRED_B 46
#define COLOR_AJAXRED_HEX COLOR_AJAXRED_R << 16 | COLOR_AJAXRED_G  << 8 | COLOR_AJAXRED_B


#define COLOR_ALABASTER_R 254
#define COLOR_ALABASTER_G 249
#define COLOR_ALABASTER_B 243
#define COLOR_ALABASTER_HEX COLOR_ALABASTER_R << 16 | COLOR_ALABASTER_G  << 8 | COLOR_ALABASTER_B


#define COLOR_ALICEBLUE_R 240
#define COLOR_ALICEBLUE_G 248
#define COLOR_ALICEBLUE_B 255
#define COLOR_ALICEBLUE_HEX COLOR_ALICEBLUE_R << 16 | COLOR_ALICEBLUE_G  << 8 | COLOR_ALICEBLUE_B


#define COLOR_ALIENBLACK_R 26
#define COLOR_ALIENBLACK_G 34
#define COLOR_ALIENBLACK_B 40
#define COLOR_ALIENBLACK_HEX COLOR_ALIENBLACK_R << 16 | COLOR_ALIENBLACK_G  << 8 | COLOR_ALIENBLACK_B


#define COLOR_ALLOYORANGE_R 195
#define COLOR_ALLOYORANGE_G 82
#define COLOR_ALLOYORANGE_B 20
#define COLOR_ALLOYORANGE_HEX COLOR_ALLOYORANGE_R << 16 | COLOR_ALLOYORANGE_G  << 8 | COLOR_ALLOYORANGE_B


#define COLOR_AMARANTH_R 229
#define COLOR_AMARANTH_G 43
#define COLOR_AMARANTH_B 80
#define COLOR_AMARANTH_HEX COLOR_AMARANTH_R << 16 | COLOR_AMARANTH_G  << 8 | COLOR_AMARANTH_B


#define COLOR_AMAZON_R 59
#define COLOR_AMAZON_G 122
#define COLOR_AMAZON_B 87
#define COLOR_AMAZON_HEX COLOR_AMAZON_R << 16 | COLOR_AMAZON_G  << 8 | COLOR_AMAZON_B


#define COLOR_AMBER_R 137
#define COLOR_AMBER_G 49
#define COLOR_AMBER_B 1
#define COLOR_AMBER_HEX COLOR_AMBER_R << 16 | COLOR_AMBER_G  << 8 | COLOR_AMBER_B


#define COLOR_AMETHYST_R 164
#define COLOR_AMETHYST_G 94
#define COLOR_AMETHYST_B 229
#define COLOR_AMETHYST_HEX COLOR_AMETHYST_R << 16 | COLOR_AMETHYST_G  << 8 | COLOR_AMETHYST_B


#define COLOR_ANCHOR_R 65
#define COLOR_ANCHOR_G 66
#define COLOR_ANCHOR_B 76
#define COLOR_ANCHOR_HEX COLOR_ANCHOR_R << 16 | COLOR_ANCHOR_G  << 8 | COLOR_ANCHOR_B


#define COLOR_ANTIFLASHWHITE_R 242
#define COLOR_ANTIFLASHWHITE_G 243
#define COLOR_ANTIFLASHWHITE_B 244
#define COLOR_ANTIFLASHWHITE_HEX COLOR_ANTIFLASHWHITE_R << 16 | COLOR_ANTIFLASHWHITE_G  << 8 | COLOR_ANTIFLASHWHITE_B


#define COLOR_ANTIQUEBRASS_R 205
#define COLOR_ANTIQUEBRASS_G 149
#define COLOR_ANTIQUEBRASS_B 117
#define COLOR_ANTIQUEBRASS_HEX COLOR_ANTIQUEBRASS_R << 16 | COLOR_ANTIQUEBRASS_G  << 8 | COLOR_ANTIQUEBRASS_B


#define COLOR_ANTIQUEWHITE_R 250
#define COLOR_ANTIQUEWHITE_G 235
#define COLOR_ANTIQUEWHITE_B 215
#define COLOR_ANTIQUEWHITE_HEX COLOR_ANTIQUEWHITE_R << 16 | COLOR_ANTIQUEWHITE_G  << 8 | COLOR_ANTIQUEWHITE_B


#define COLOR_APPLE_R 169
#define COLOR_APPLE_G 27
#define COLOR_APPLE_B 13
#define COLOR_APPLE_HEX COLOR_APPLE_R << 16 | COLOR_APPLE_G  << 8 | COLOR_APPLE_B


#define COLOR_APRICOT_R 237
#define COLOR_APRICOT_G 130
#define COLOR_APRICOT_B 14
#define COLOR_APRICOT_HEX COLOR_APRICOT_R << 16 | COLOR_APRICOT_G  << 8 | COLOR_APRICOT_B


#define COLOR_AQUA_R 0
#define COLOR_AQUA_G 255
#define COLOR_AQUA_B 255
#define COLOR_AQUA_HEX COLOR_AQUA_R << 16 | COLOR_AQUA_G  << 8 | COLOR_AQUA_B


#define COLOR_AQUAMARINE_R 127
#define COLOR_AQUAMARINE_G 255
#define COLOR_AQUAMARINE_B 212
#define COLOR_AQUAMARINE_HEX COLOR_AQUAMARINE_R << 16 | COLOR_AQUAMARINE_G  << 8 | COLOR_AQUAMARINE_B


#define COLOR_ARCTIC_R 130
#define COLOR_ARCTIC_G 238
#define COLOR_ARCTIC_B 253
#define COLOR_ARCTIC_HEX COLOR_ARCTIC_R << 16 | COLOR_ARCTIC_G  << 8 | COLOR_ARCTIC_B


#define COLOR_ARMYGREEN_R 75
#define COLOR_ARMYGREEN_G 83
#define COLOR_ARMYGREEN_B 32
#define COLOR_ARMYGREEN_HEX COLOR_ARMYGREEN_R << 16 | COLOR_ARMYGREEN_G  << 8 | COLOR_ARMYGREEN_B


#define COLOR_ARSENIC_R 59
#define COLOR_ARSENIC_G 68
#define COLOR_ARSENIC_B 75
#define COLOR_ARSENIC_HEX COLOR_ARSENIC_R << 16 | COLOR_ARSENIC_G  << 8 | COLOR_ARSENIC_B


#define COLOR_ARTICHOKEGREEN_R 143
#define COLOR_ARTICHOKEGREEN_G 151
#define COLOR_ARTICHOKEGREEN_B 121
#define COLOR_ARTICHOKEGREEN_HEX COLOR_ARTICHOKEGREEN_R << 16 | COLOR_ARTICHOKEGREEN_G  << 8 | COLOR_ARTICHOKEGREEN_B


#define COLOR_ASH_R 86
#define COLOR_ASH_G 76
#define COLOR_ASH_B 77
#define COLOR_ASH_HEX COLOR_ASH_R << 16 | COLOR_ASH_G  << 8 | COLOR_ASH_B


#define COLOR_ASPHALT_R 12
#define COLOR_ASPHALT_G 4
#define COLOR_ASPHALT_B 4
#define COLOR_ASPHALT_HEX COLOR_ASPHALT_R << 16 | COLOR_ASPHALT_G  << 8 | COLOR_ASPHALT_B


#define COLOR_AVOCADO_R 86
#define COLOR_AVOCADO_G 130
#define COLOR_AVOCADO_B 3
#define COLOR_AVOCADO_HEX COLOR_AVOCADO_R << 16 | COLOR_AVOCADO_G  << 8 | COLOR_AVOCADO_B


#define COLOR_AZURE_R 240
#define COLOR_AZURE_G 255
#define COLOR_AZURE_B 255
#define COLOR_AZURE_HEX COLOR_AZURE_R << 16 | COLOR_AZURE_G  << 8 | COLOR_AZURE_B


#define COLOR_BABYBLUE_R 137
#define COLOR_BABYBLUE_G 207
#define COLOR_BABYBLUE_B 240
#define COLOR_BABYBLUE_HEX COLOR_BABYBLUE_R << 16 | COLOR_BABYBLUE_G  << 8 | COLOR_BABYBLUE_B


#define COLOR_BABYPINK_R 244
#define COLOR_BABYPINK_G 194
#define COLOR_BABYPINK_B 194
#define COLOR_BABYPINK_HEX COLOR_BABYPINK_R << 16 | COLOR_BABYPINK_G  << 8 | COLOR_BABYPINK_B


#define COLOR_BABYPOWDER_R 254
#define COLOR_BABYPOWDER_G 254
#define COLOR_BABYPOWDER_B 250
#define COLOR_BABYPOWDER_HEX COLOR_BABYPOWDER_R << 16 | COLOR_BABYPOWDER_G  << 8 | COLOR_BABYPOWDER_B


#define COLOR_BALLETSLIPPER_R 247
#define COLOR_BALLETSLIPPER_G 154
#define COLOR_BALLETSLIPPER_B 192
#define COLOR_BALLETSLIPPER_HEX COLOR_BALLETSLIPPER_R << 16 | COLOR_BALLETSLIPPER_G  << 8 | COLOR_BALLETSLIPPER_B


#define COLOR_BANANA_R 255
#define COLOR_BANANA_G 225
#define COLOR_BANANA_B 53
#define COLOR_BANANA_HEX COLOR_BANANA_R << 16 | COLOR_BANANA_G  << 8 | COLOR_BANANA_B


#define COLOR_BARK_R 128
#define COLOR_BARK_G 71
#define COLOR_BARK_B 28
#define COLOR_BARK_HEX COLOR_BARK_R << 16 | COLOR_BARK_G  << 8 | COLOR_BARK_B


#define COLOR_BASIL_R 50
#define COLOR_BASIL_G 97
#define COLOR_BASIL_B 45
#define COLOR_BASIL_HEX COLOR_BASIL_R << 16 | COLOR_BASIL_G  << 8 | COLOR_BASIL_B


#define COLOR_BATTLESHIPGRAY_R 132
#define COLOR_BATTLESHIPGRAY_G 132
#define COLOR_BATTLESHIPGRAY_B 130
#define COLOR_BATTLESHIPGRAY_HEX COLOR_BATTLESHIPGRAY_R << 16 | COLOR_BATTLESHIPGRAY_G  << 8 | COLOR_BATTLESHIPGRAY_B


#define COLOR_BDAZZLED_R 46
#define COLOR_BDAZZLED_G 88
#define COLOR_BDAZZLED_B 148
#define COLOR_BDAZZLED_HEX COLOR_BDAZZLED_R << 16 | COLOR_BDAZZLED_G  << 8 | COLOR_BDAZZLED_B


#define COLOR_BEAUBLUE_R 188
#define COLOR_BEAUBLUE_G 212
#define COLOR_BEAUBLUE_B 230
#define COLOR_BEAUBLUE_HEX COLOR_BEAUBLUE_R << 16 | COLOR_BEAUBLUE_G  << 8 | COLOR_BEAUBLUE_B


#define COLOR_BEAVER_R 159
#define COLOR_BEAVER_G 129
#define COLOR_BEAVER_B 112
#define COLOR_BEAVER_HEX COLOR_BEAVER_R << 16 | COLOR_BEAVER_G  << 8 | COLOR_BEAVER_B


#define COLOR_BEIGE_R 245
#define COLOR_BEIGE_G 245
#define COLOR_BEIGE_B 220
#define COLOR_BEIGE_HEX COLOR_BEIGE_R << 16 | COLOR_BEIGE_G  << 8 | COLOR_BEIGE_B


#define COLOR_BEIGEYELLOW_R 238
#define COLOR_BEIGEYELLOW_G 220
#define COLOR_BEIGEYELLOW_B 154
#define COLOR_BEIGEYELLOW_HEX COLOR_BEIGEYELLOW_R << 16 | COLOR_BEIGEYELLOW_G  << 8 | COLOR_BEIGEYELLOW_B


#define COLOR_BERRY_R 122
#define COLOR_BERRY_G 23
#define COLOR_BERRY_B 18
#define COLOR_BERRY_HEX COLOR_BERRY_R << 16 | COLOR_BERRY_G  << 8 | COLOR_BERRY_B


#define COLOR_BISCOTTI_R 227
#define COLOR_BISCOTTI_G 197
#define COLOR_BISCOTTI_B 101
#define COLOR_BISCOTTI_HEX COLOR_BISCOTTI_R << 16 | COLOR_BISCOTTI_G  << 8 | COLOR_BISCOTTI_B


#define COLOR_BISQUE_R 255
#define COLOR_BISQUE_G 228
#define COLOR_BISQUE_B 196
#define COLOR_BISQUE_HEX COLOR_BISQUE_R << 16 | COLOR_BISQUE_G  << 8 | COLOR_BISQUE_B


#define COLOR_BISTRE_R 61
#define COLOR_BISTRE_G 43
#define COLOR_BISTRE_B 31
#define COLOR_BISTRE_HEX COLOR_BISTRE_R << 16 | COLOR_BISTRE_G  << 8 | COLOR_BISTRE_B


#define COLOR_BLACK_R 0
#define COLOR_BLACK_G 0
#define COLOR_BLACK_B 0
#define COLOR_BLACK_HEX COLOR_BLACK_R << 16 | COLOR_BLACK_G  << 8 | COLOR_BLACK_B


#define COLOR_BLACKCHOCOLATE_R 27
#define COLOR_BLACKCHOCOLATE_G 24
#define COLOR_BLACKCHOCOLATE_B 17
#define COLOR_BLACKCHOCOLATE_HEX COLOR_BLACKCHOCOLATE_R << 16 | COLOR_BLACKCHOCOLATE_G  << 8 | COLOR_BLACKCHOCOLATE_B


#define COLOR_BLACKDENIM_R 25
#define COLOR_BLACKDENIM_G 28
#define COLOR_BLACKDENIM_B 39
#define COLOR_BLACKDENIM_HEX COLOR_BLACKDENIM_R << 16 | COLOR_BLACKDENIM_G  << 8 | COLOR_BLACKDENIM_B


#define COLOR_BLACKMAGIC_R 11
#define COLOR_BLACKMAGIC_G 5
#define COLOR_BLACKMAGIC_B 16
#define COLOR_BLACKMAGIC_HEX COLOR_BLACKMAGIC_R << 16 | COLOR_BLACKMAGIC_G  << 8 | COLOR_BLACKMAGIC_B


#define COLOR_BLACKOIL_R 35
#define COLOR_BLACKOIL_G 23
#define COLOR_BLACKOIL_B 9
#define COLOR_BLACKOIL_HEX COLOR_BLACKOIL_R << 16 | COLOR_BLACKOIL_G  << 8 | COLOR_BLACKOIL_B


#define COLOR_BLACKROCK_R 1
#define COLOR_BLACKROCK_G 1
#define COLOR_BLACKROCK_B 39
#define COLOR_BLACKROCK_HEX COLOR_BLACKROCK_R << 16 | COLOR_BLACKROCK_G  << 8 | COLOR_BLACKROCK_B


#define COLOR_BLANCHEDALMOND_R 255
#define COLOR_BLANCHEDALMOND_G 235
#define COLOR_BLANCHEDALMOND_B 205
#define COLOR_BLANCHEDALMOND_HEX COLOR_BLANCHEDALMOND_R << 16 | COLOR_BLANCHEDALMOND_G  << 8 | COLOR_BLANCHEDALMOND_B


#define COLOR_BLUE_R 0
#define COLOR_BLUE_G 0
#define COLOR_BLUE_B 255
#define COLOR_BLUE_HEX COLOR_BLUE_R << 16 | COLOR_BLUE_G  << 8 | COLOR_BLUE_B


#define COLOR_BLUEBERRY_R 36
#define COLOR_BLUEBERRY_G 21
#define COLOR_BLUEBERRY_B 113
#define COLOR_BLUEBERRY_HEX COLOR_BLUEBERRY_R << 16 | COLOR_BLUEBERRY_G  << 8 | COLOR_BLUEBERRY_B


#define COLOR_BLUESAPPHIRE_R 18
#define COLOR_BLUESAPPHIRE_G 97
#define COLOR_BLUESAPPHIRE_B 128
#define COLOR_BLUESAPPHIRE_HEX COLOR_BLUESAPPHIRE_R << 16 | COLOR_BLUESAPPHIRE_G  << 8 | COLOR_BLUESAPPHIRE_B


#define COLOR_BLUSHPINK_R 254
#define COLOR_BLUSHPINK_G 197
#define COLOR_BLUSHPINK_B 229
#define COLOR_BLUSHPINK_HEX COLOR_BLUSHPINK_R << 16 | COLOR_BLUSHPINK_G  << 8 | COLOR_BLUSHPINK_B


#define COLOR_BLUSHRED_R 188
#define COLOR_BLUSHRED_G 84
#define COLOR_BLUSHRED_B 75
#define COLOR_BLUSHRED_HEX COLOR_BLUSHRED_R << 16 | COLOR_BLUSHRED_G  << 8 | COLOR_BLUSHRED_B


#define COLOR_BOLE_R 121
#define COLOR_BOLE_G 68
#define COLOR_BOLE_B 59
#define COLOR_BOLE_HEX COLOR_BOLE_R << 16 | COLOR_BOLE_G  << 8 | COLOR_BOLE_B


#define COLOR_BONE_R 231
#define COLOR_BONE_G 222
#define COLOR_BONE_B 204
#define COLOR_BONE_HEX COLOR_BONE_R << 16 | COLOR_BONE_G  << 8 | COLOR_BONE_B


#define COLOR_BOYSENBERRY_R 99
#define COLOR_BOYSENBERRY_G 4
#define COLOR_BOYSENBERRY_B 54
#define COLOR_BOYSENBERRY_HEX COLOR_BOYSENBERRY_R << 16 | COLOR_BOYSENBERRY_G  << 8 | COLOR_BOYSENBERRY_B


#define COLOR_BRICK_R 126
#define COLOR_BRICK_G 40
#define COLOR_BRICK_B 17
#define COLOR_BRICK_HEX COLOR_BRICK_R << 16 | COLOR_BRICK_G  << 8 | COLOR_BRICK_B


#define COLOR_BRIGHTPINK_R 255
#define COLOR_BRIGHTPINK_G 0
#define COLOR_BRIGHTPINK_B 127
#define COLOR_BRIGHTPINK_HEX COLOR_BRIGHTPINK_R << 16 | COLOR_BRIGHTPINK_G  << 8 | COLOR_BRIGHTPINK_B


#define COLOR_BRIGHTYELLOW_R 255
#define COLOR_BRIGHTYELLOW_G 253
#define COLOR_BRIGHTYELLOW_B 1
#define COLOR_BRIGHTYELLOW_HEX COLOR_BRIGHTYELLOW_R << 16 | COLOR_BRIGHTYELLOW_G  << 8 | COLOR_BRIGHTYELLOW_B


#define COLOR_BRONZE_R 178
#define COLOR_BRONZE_G 86
#define COLOR_BRONZE_B 13
#define COLOR_BRONZE_HEX COLOR_BRONZE_R << 16 | COLOR_BRONZE_G  << 8 | COLOR_BRONZE_B


#define COLOR_BROWN_R 165
#define COLOR_BROWN_G 42
#define COLOR_BROWN_B 42
#define COLOR_BROWN_HEX COLOR_BROWN_R << 16 | COLOR_BROWN_G  << 8 | COLOR_BROWN_B


#define COLOR_BRUNETTE_R 59
#define COLOR_BRUNETTE_G 30
#define COLOR_BRUNETTE_B 8
#define COLOR_BRUNETTE_HEX COLOR_BRUNETTE_R << 16 | COLOR_BRUNETTE_G  << 8 | COLOR_BRUNETTE_B


#define COLOR_BUBBLEGUM_R 253
#define COLOR_BUBBLEGUM_G 93
#define COLOR_BUBBLEGUM_B 168
#define COLOR_BUBBLEGUM_HEX COLOR_BUBBLEGUM_R << 16 | COLOR_BUBBLEGUM_G  << 8 | COLOR_BUBBLEGUM_B


#define COLOR_BUMBLEBEE_R 252
#define COLOR_BUMBLEBEE_G 226
#define COLOR_BUMBLEBEE_B 5
#define COLOR_BUMBLEBEE_HEX COLOR_BUMBLEBEE_R << 16 | COLOR_BUMBLEBEE_G  << 8 | COLOR_BUMBLEBEE_B


#define COLOR_BURGUNDY_R 141
#define COLOR_BURGUNDY_G 2
#define COLOR_BURGUNDY_B 31
#define COLOR_BURGUNDY_HEX COLOR_BURGUNDY_R << 16 | COLOR_BURGUNDY_G  << 8 | COLOR_BURGUNDY_B


#define COLOR_BURLYWOOD_R 222
#define COLOR_BURLYWOOD_G 184
#define COLOR_BURLYWOOD_B 135
#define COLOR_BURLYWOOD_HEX COLOR_BURLYWOOD_R << 16 | COLOR_BURLYWOOD_G  << 8 | COLOR_BURLYWOOD_B


#define COLOR_BURNTUMBER_R 138
#define COLOR_BURNTUMBER_G 51
#define COLOR_BURNTUMBER_B 36
#define COLOR_BURNTUMBER_HEX COLOR_BURNTUMBER_R << 16 | COLOR_BURNTUMBER_G  << 8 | COLOR_BURNTUMBER_B


#define COLOR_BUTTER_R 255
#define COLOR_BUTTER_G 253
#define COLOR_BUTTER_B 116
#define COLOR_BUTTER_HEX COLOR_BUTTER_R << 16 | COLOR_BUTTER_G  << 8 | COLOR_BUTTER_B


#define COLOR_BUTTERMILK_R 253
#define COLOR_BUTTERMILK_G 239
#define COLOR_BUTTERMILK_B 178
#define COLOR_BUTTERMILK_HEX COLOR_BUTTERMILK_R << 16 | COLOR_BUTTERMILK_G  << 8 | COLOR_BUTTERMILK_B


#define COLOR_BYZANTIUM_R 112
#define COLOR_BYZANTIUM_G 41
#define COLOR_BYZANTIUM_B 99
#define COLOR_BYZANTIUM_HEX COLOR_BYZANTIUM_R << 16 | COLOR_BYZANTIUM_G  << 8 | COLOR_BYZANTIUM_B


#define COLOR_CADETBLUE_R 95
#define COLOR_CADETBLUE_G 158
#define COLOR_CADETBLUE_B 160
#define COLOR_CADETBLUE_HEX COLOR_CADETBLUE_R << 16 | COLOR_CADETBLUE_G  << 8 | COLOR_CADETBLUE_B


#define COLOR_CAFEAULAIT_R 166
#define COLOR_CAFEAULAIT_G 123
#define COLOR_CAFEAULAIT_B 91
#define COLOR_CAFEAULAIT_HEX COLOR_CAFEAULAIT_R << 16 | COLOR_CAFEAULAIT_G  << 8 | COLOR_CAFEAULAIT_B


#define COLOR_CAFENOIR_R 75
#define COLOR_CAFENOIR_G 54
#define COLOR_CAFENOIR_B 33
#define COLOR_CAFENOIR_HEX COLOR_CAFENOIR_R << 16 | COLOR_CAFENOIR_G  << 8 | COLOR_CAFENOIR_B


#define COLOR_CAMEOPINK_R 239
#define COLOR_CAMEOPINK_G 187
#define COLOR_CAMEOPINK_B 204
#define COLOR_CAMEOPINK_HEX COLOR_CAMEOPINK_R << 16 | COLOR_CAMEOPINK_G  << 8 | COLOR_CAMEOPINK_B


#define COLOR_CANARYYELLOW_R 255
#define COLOR_CANARYYELLOW_G 239
#define COLOR_CANARYYELLOW_B 0
#define COLOR_CANARYYELLOW_HEX COLOR_CANARYYELLOW_R << 16 | COLOR_CANARYYELLOW_G  << 8 | COLOR_CANARYYELLOW_B


#define COLOR_CANDY_R 210
#define COLOR_CANDY_G 20
#define COLOR_CANDY_B 4
#define COLOR_CANDY_HEX COLOR_CANDY_R << 16 | COLOR_CANDY_G  << 8 | COLOR_CANDY_B


#define COLOR_CANDYAPPLE_R 255
#define COLOR_CANDYAPPLE_G 8
#define COLOR_CANDYAPPLE_B 0
#define COLOR_CANDYAPPLE_HEX COLOR_CANDYAPPLE_R << 16 | COLOR_CANDYAPPLE_G  << 8 | COLOR_CANDYAPPLE_B


#define COLOR_CANDYPINK_R 228
#define COLOR_CANDYPINK_G 113
#define COLOR_CANDYPINK_B 122
#define COLOR_CANDYPINK_HEX COLOR_CANDYPINK_R << 16 | COLOR_CANDYPINK_G  << 8 | COLOR_CANDYPINK_B


#define COLOR_CANTALOUPE_R 253
#define COLOR_CANTALOUPE_G 161
#define COLOR_CANTALOUPE_B 114
#define COLOR_CANTALOUPE_HEX COLOR_CANTALOUPE_R << 16 | COLOR_CANTALOUPE_G  << 8 | COLOR_CANTALOUPE_B


#define COLOR_CARAMEL_R 101
#define COLOR_CARAMEL_G 53
#define COLOR_CARAMEL_B 15
#define COLOR_CARAMEL_HEX COLOR_CARAMEL_R << 16 | COLOR_CARAMEL_G  << 8 | COLOR_CARAMEL_B


#define COLOR_CARBONGRAY_R 98
#define COLOR_CARBONGRAY_G 93
#define COLOR_CARBONGRAY_B 93
#define COLOR_CARBONGRAY_HEX COLOR_CARBONGRAY_R << 16 | COLOR_CARBONGRAY_G  << 8 | COLOR_CARBONGRAY_B


#define COLOR_CARDINALSRED_R 189
#define COLOR_CARDINALSRED_G 32
#define COLOR_CARDINALSRED_B 49
#define COLOR_CARDINALSRED_HEX COLOR_CARDINALSRED_R << 16 | COLOR_CARDINALSRED_G  << 8 | COLOR_CARDINALSRED_B


#define COLOR_CARMINE_R 150
#define COLOR_CARMINE_G 0
#define COLOR_CARMINE_B 24
#define COLOR_CARMINE_HEX COLOR_CARMINE_R << 16 | COLOR_CARMINE_G  << 8 | COLOR_CARMINE_B


#define COLOR_CARNATION_R 255
#define COLOR_CARNATION_G 166
#define COLOR_CARNATION_B 201
#define COLOR_CARNATION_HEX COLOR_CARNATION_R << 16 | COLOR_CARNATION_G  << 8 | COLOR_CARNATION_B


#define COLOR_CAROB_R 54
#define COLOR_CAROB_G 37
#define COLOR_CAROB_B 17
#define COLOR_CAROB_HEX COLOR_CAROB_R << 16 | COLOR_CAROB_G  << 8 | COLOR_CAROB_B


#define COLOR_CAROLINABLUE_R 75
#define COLOR_CAROLINABLUE_G 156
#define COLOR_CAROLINABLUE_B 211
#define COLOR_CAROLINABLUE_HEX COLOR_CAROLINABLUE_R << 16 | COLOR_CAROLINABLUE_G  << 8 | COLOR_CAROLINABLUE_B


#define COLOR_CARROT_R 237
#define COLOR_CARROT_G 113
#define COLOR_CARROT_B 23
#define COLOR_CARROT_HEX COLOR_CARROT_R << 16 | COLOR_CARROT_G  << 8 | COLOR_CARROT_B


#define COLOR_CASCADINGWHITE_R 247
#define COLOR_CASCADINGWHITE_G 245
#define COLOR_CASCADINGWHITE_B 246
#define COLOR_CASCADINGWHITE_HEX COLOR_CASCADINGWHITE_R << 16 | COLOR_CASCADINGWHITE_G  << 8 | COLOR_CASCADINGWHITE_B


#define COLOR_CEDARBROWN_R 74
#define COLOR_CEDARBROWN_G 55
#define COLOR_CEDARBROWN_B 40
#define COLOR_CEDARBROWN_HEX COLOR_CEDARBROWN_R << 16 | COLOR_CEDARBROWN_G  << 8 | COLOR_CEDARBROWN_B


#define COLOR_CELADON_R 172
#define COLOR_CELADON_G 225
#define COLOR_CELADON_B 175
#define COLOR_CELADON_HEX COLOR_CELADON_R << 16 | COLOR_CELADON_G  << 8 | COLOR_CELADON_B


#define COLOR_CERULEAN_R 4
#define COLOR_CERULEAN_G 146
#define COLOR_CERULEAN_B 194
#define COLOR_CERULEAN_HEX COLOR_CERULEAN_R << 16 | COLOR_CERULEAN_G  << 8 | COLOR_CERULEAN_B


#define COLOR_CHARCOAL_R 40
#define COLOR_CHARCOAL_G 35
#define COLOR_CHARCOAL_B 29
#define COLOR_CHARCOAL_HEX COLOR_CHARCOAL_R << 16 | COLOR_CHARCOAL_G  << 8 | COLOR_CHARCOAL_B


#define COLOR_CHARCOALGRAY_R 35
#define COLOR_CHARCOALGRAY_G 32
#define COLOR_CHARCOALGRAY_B 35
#define COLOR_CHARCOALGRAY_HEX COLOR_CHARCOALGRAY_R << 16 | COLOR_CHARCOALGRAY_G  << 8 | COLOR_CHARCOALGRAY_B


#define COLOR_CHARLESTONGREEN_R 35
#define COLOR_CHARLESTONGREEN_G 43
#define COLOR_CHARLESTONGREEN_B 43
#define COLOR_CHARLESTONGREEN_HEX COLOR_CHARLESTONGREEN_R << 16 | COLOR_CHARLESTONGREEN_G  << 8 | COLOR_CHARLESTONGREEN_B


#define COLOR_CHARTREUSE_R 223
#define COLOR_CHARTREUSE_G 255
#define COLOR_CHARTREUSE_B 0
#define COLOR_CHARTREUSE_HEX COLOR_CHARTREUSE_R << 16 | COLOR_CHARTREUSE_G  << 8 | COLOR_CHARTREUSE_B


#define COLOR_CHATEAU_R 72
#define COLOR_CHATEAU_G 168
#define COLOR_CHATEAU_B 96
#define COLOR_CHATEAU_HEX COLOR_CHATEAU_R << 16 | COLOR_CHATEAU_G  << 8 | COLOR_CHATEAU_B


#define COLOR_CHERRYBLOSSOM_R 255
#define COLOR_CHERRYBLOSSOM_G 183
#define COLOR_CHERRYBLOSSOM_B 197
#define COLOR_CHERRYBLOSSOM_HEX COLOR_CHERRYBLOSSOM_R << 16 | COLOR_CHERRYBLOSSOM_G  << 8 | COLOR_CHERRYBLOSSOM_B


#define COLOR_CHERRYPINK_R 222
#define COLOR_CHERRYPINK_G 49
#define COLOR_CHERRYPINK_B 99
#define COLOR_CHERRYPINK_HEX COLOR_CHERRYPINK_R << 16 | COLOR_CHERRYPINK_G  << 8 | COLOR_CHERRYPINK_B


#define COLOR_CHERRYRED_R 153
#define COLOR_CHERRYRED_G 15
#define COLOR_CHERRYRED_B 2
#define COLOR_CHERRYRED_HEX COLOR_CHERRYRED_R << 16 | COLOR_CHERRYRED_G  << 8 | COLOR_CHERRYRED_B


#define COLOR_CHIFFON_R 251
#define COLOR_CHIFFON_G 250
#define COLOR_CHIFFON_B 242
#define COLOR_CHIFFON_HEX COLOR_CHIFFON_R << 16 | COLOR_CHIFFON_G  << 8 | COLOR_CHIFFON_B


#define COLOR_CHILIRED_R 194
#define COLOR_CHILIRED_G 24
#define COLOR_CHILIRED_B 7
#define COLOR_CHILIRED_HEX COLOR_CHILIRED_R << 16 | COLOR_CHILIRED_G  << 8 | COLOR_CHILIRED_B


#define COLOR_CHOCOLATE_R 210
#define COLOR_CHOCOLATE_G 105
#define COLOR_CHOCOLATE_B 30
#define COLOR_CHOCOLATE_HEX COLOR_CHOCOLATE_R << 16 | COLOR_CHOCOLATE_G  << 8 | COLOR_CHOCOLATE_B


#define COLOR_CIDER_R 181
#define COLOR_CIDER_G 103
#define COLOR_CIDER_B 39
#define COLOR_CIDER_HEX COLOR_CIDER_R << 16 | COLOR_CIDER_G  << 8 | COLOR_CIDER_B


#define COLOR_CINNAMONBROWN_R 101
#define COLOR_CINNAMONBROWN_G 42
#define COLOR_CINNAMONBROWN_B 14
#define COLOR_CINNAMONBROWN_HEX COLOR_CINNAMONBROWN_R << 16 | COLOR_CINNAMONBROWN_G  << 8 | COLOR_CINNAMONBROWN_B


#define COLOR_CITRINE_R 228
#define COLOR_CITRINE_G 208
#define COLOR_CITRINE_B 10
#define COLOR_CITRINE_HEX COLOR_CITRINE_R << 16 | COLOR_CITRINE_G  << 8 | COLOR_CITRINE_B


#define COLOR_CLAY_R 128
#define COLOR_CLAY_G 64
#define COLOR_CLAY_B 11
#define COLOR_CLAY_HEX COLOR_CLAY_R << 16 | COLOR_CLAY_G  << 8 | COLOR_CLAY_B


#define COLOR_CLOUD_R 197
#define COLOR_CLOUD_G 198
#define COLOR_CLOUD_B 208
#define COLOR_CLOUD_HEX COLOR_CLOUD_R << 16 | COLOR_CLOUD_G  << 8 | COLOR_CLOUD_B


#define COLOR_CLOVERLIME_R 252
#define COLOR_CLOVERLIME_G 232
#define COLOR_CLOVERLIME_B 131
#define COLOR_CLOVERLIME_HEX COLOR_CLOVERLIME_R << 16 | COLOR_CLOVERLIME_G  << 8 | COLOR_CLOVERLIME_B


#define COLOR_COAL_R 12
#define COLOR_COAL_G 9
#define COLOR_COAL_B 8
#define COLOR_COAL_HEX COLOR_COAL_R << 16 | COLOR_COAL_G  << 8 | COLOR_COAL_B


#define COLOR_COBALT_R 19
#define COLOR_COBALT_G 56
#define COLOR_COBALT_B 190
#define COLOR_COBALT_HEX COLOR_COBALT_R << 16 | COLOR_COBALT_G  << 8 | COLOR_COBALT_B


#define COLOR_COCONUTMILK_R 255
#define COLOR_COCONUTMILK_G 241
#define COLOR_COCONUTMILK_B 230
#define COLOR_COCONUTMILK_HEX COLOR_COCONUTMILK_R << 16 | COLOR_COCONUTMILK_G  << 8 | COLOR_COCONUTMILK_B


#define COLOR_COFFEE_R 111
#define COLOR_COFFEE_G 78
#define COLOR_COFFEE_B 55
#define COLOR_COFFEE_HEX COLOR_COFFEE_R << 16 | COLOR_COFFEE_G  << 8 | COLOR_COFFEE_B


#define COLOR_COIN_R 152
#define COLOR_COIN_G 151
#define COLOR_COIN_B 169
#define COLOR_COIN_HEX COLOR_COIN_R << 16 | COLOR_COIN_G  << 8 | COLOR_COIN_B


#define COLOR_COOLBLACK_R 21
#define COLOR_COOLBLACK_G 25
#define COLOR_COOLBLACK_B 34
#define COLOR_COOLBLACK_HEX COLOR_COOLBLACK_R << 16 | COLOR_COOLBLACK_G  << 8 | COLOR_COOLBLACK_B


#define COLOR_COPPER_R 184
#define COLOR_COPPER_G 115
#define COLOR_COPPER_B 51
#define COLOR_COPPER_HEX COLOR_COPPER_R << 16 | COLOR_COPPER_G  << 8 | COLOR_COPPER_B


#define COLOR_CORAL_R 255
#define COLOR_CORAL_G 127
#define COLOR_CORAL_B 80
#define COLOR_CORAL_HEX COLOR_CORAL_R << 16 | COLOR_CORAL_G  << 8 | COLOR_CORAL_B


#define COLOR_CORALPINK_R 254
#define COLOR_CORALPINK_G 125
#define COLOR_CORALPINK_B 106
#define COLOR_CORALPINK_HEX COLOR_CORALPINK_R << 16 | COLOR_CORALPINK_G  << 8 | COLOR_CORALPINK_B


#define COLOR_CORNFLOWERBLUE_R 100
#define COLOR_CORNFLOWERBLUE_G 149
#define COLOR_CORNFLOWERBLUE_B 237
#define COLOR_CORNFLOWERBLUE_HEX COLOR_CORNFLOWERBLUE_R << 16 | COLOR_CORNFLOWERBLUE_G  << 8 | COLOR_CORNFLOWERBLUE_B


#define COLOR_CORNSILK_R 255
#define COLOR_CORNSILK_G 248
#define COLOR_CORNSILK_B 220
#define COLOR_CORNSILK_HEX COLOR_CORNSILK_R << 16 | COLOR_CORNSILK_G  << 8 | COLOR_CORNSILK_B


#define COLOR_COTTON_R 251
#define COLOR_COTTON_G 251
#define COLOR_COTTON_B 249
#define COLOR_COTTON_HEX COLOR_COTTON_R << 16 | COLOR_COTTON_G  << 8 | COLOR_COTTON_B


#define COLOR_COTTONCANDY_R 255
#define COLOR_COTTONCANDY_G 188
#define COLOR_COTTONCANDY_B 217
#define COLOR_COTTONCANDY_HEX COLOR_COTTONCANDY_R << 16 | COLOR_COTTONCANDY_G  << 8 | COLOR_COTTONCANDY_B


#define COLOR_COUGHMIXTURE_R 246
#define COLOR_COUGHMIXTURE_G 244
#define COLOR_COUGHMIXTURE_B 241
#define COLOR_COUGHMIXTURE_HEX COLOR_COUGHMIXTURE_R << 16 | COLOR_COUGHMIXTURE_G  << 8 | COLOR_COUGHMIXTURE_B


#define COLOR_CREAM_R 255
#define COLOR_CREAM_G 250
#define COLOR_CREAM_B 218
#define COLOR_CREAM_HEX COLOR_CREAM_R << 16 | COLOR_CREAM_G  << 8 | COLOR_CREAM_B


#define COLOR_CRIMSON_R 220
#define COLOR_CRIMSON_G 20
#define COLOR_CRIMSON_B 60
#define COLOR_CRIMSON_HEX COLOR_CRIMSON_R << 16 | COLOR_CRIMSON_G  << 8 | COLOR_CRIMSON_B


#define COLOR_CRIMSONCHIN_R 185
#define COLOR_CRIMSONCHIN_G 14
#define COLOR_CRIMSONCHIN_B 10
#define COLOR_CRIMSONCHIN_HEX COLOR_CRIMSONCHIN_R << 16 | COLOR_CRIMSONCHIN_G  << 8 | COLOR_CRIMSONCHIN_B


#define COLOR_CROCODILE_R 96
#define COLOR_CROCODILE_G 125
#define COLOR_CROCODILE_B 59
#define COLOR_CROCODILE_HEX COLOR_CROCODILE_R << 16 | COLOR_CROCODILE_G  << 8 | COLOR_CROCODILE_B


#define COLOR_CROW_R 13
#define COLOR_CROW_G 9
#define COLOR_CROW_B 7
#define COLOR_CROW_HEX COLOR_CROW_R << 16 | COLOR_CROW_G  << 8 | COLOR_CROW_B


#define COLOR_CUPCAKE_R 235
#define COLOR_CUPCAKE_G 246
#define COLOR_CUPCAKE_B 247
#define COLOR_CUPCAKE_HEX COLOR_CUPCAKE_R << 16 | COLOR_CUPCAKE_G  << 8 | COLOR_CUPCAKE_B


#define COLOR_CURRANT_R 104
#define COLOR_CURRANT_G 12
#define COLOR_CURRANT_B 7
#define COLOR_CURRANT_HEX COLOR_CURRANT_R << 16 | COLOR_CURRANT_G  << 8 | COLOR_CURRANT_B


#define COLOR_DAISY_R 250
#define COLOR_DAISY_G 250
#define COLOR_DAISY_B 250
#define COLOR_DAISY_HEX COLOR_DAISY_R << 16 | COLOR_DAISY_G  << 8 | COLOR_DAISY_B


#define COLOR_DARKAZURE_R 21
#define COLOR_DARKAZURE_G 32
#define COLOR_DARKAZURE_B 166
#define COLOR_DARKAZURE_HEX COLOR_DARKAZURE_R << 16 | COLOR_DARKAZURE_G  << 8 | COLOR_DARKAZURE_B


#define COLOR_DARKBLUE_R 0
#define COLOR_DARKBLUE_G 0
#define COLOR_DARKBLUE_B 139
#define COLOR_DARKBLUE_HEX COLOR_DARKBLUE_R << 16 | COLOR_DARKBLUE_G  << 8 | COLOR_DARKBLUE_B


#define COLOR_DARKBROWN_R 101
#define COLOR_DARKBROWN_G 67
#define COLOR_DARKBROWN_B 33
#define COLOR_DARKBROWN_HEX COLOR_DARKBROWN_R << 16 | COLOR_DARKBROWN_G  << 8 | COLOR_DARKBROWN_B


#define COLOR_DARKCHOCOLATE_R 46
#define COLOR_DARKCHOCOLATE_G 21
#define COLOR_DARKCHOCOLATE_B 3
#define COLOR_DARKCHOCOLATE_HEX COLOR_DARKCHOCOLATE_R << 16 | COLOR_DARKCHOCOLATE_G  << 8 | COLOR_DARKCHOCOLATE_B


#define COLOR_DARKCYAN_R 0
#define COLOR_DARKCYAN_G 139
#define COLOR_DARKCYAN_B 139
#define COLOR_DARKCYAN_HEX COLOR_DARKCYAN_R << 16 | COLOR_DARKCYAN_G  << 8 | COLOR_DARKCYAN_B


#define COLOR_DARKGOLDENROD_R 184
#define COLOR_DARKGOLDENROD_G 134
#define COLOR_DARKGOLDENROD_B 11
#define COLOR_DARKGOLDENROD_HEX COLOR_DARKGOLDENROD_R << 16 | COLOR_DARKGOLDENROD_G  << 8 | COLOR_DARKGOLDENROD_B


#define COLOR_DARKGRAY_R 169
#define COLOR_DARKGRAY_G 169
#define COLOR_DARKGRAY_B 169
#define COLOR_DARKGRAY_HEX COLOR_DARKGRAY_R << 16 | COLOR_DARKGRAY_G  << 8 | COLOR_DARKGRAY_B


#define COLOR_DARKGREEN_R 0
#define COLOR_DARKGREEN_G 100
#define COLOR_DARKGREEN_B 0
#define COLOR_DARKGREEN_HEX COLOR_DARKGREEN_R << 16 | COLOR_DARKGREEN_G  << 8 | COLOR_DARKGREEN_B


#define COLOR_DARKJUNGLEGREEN_R 26
#define COLOR_DARKJUNGLEGREEN_G 36
#define COLOR_DARKJUNGLEGREEN_B 33
#define COLOR_DARKJUNGLEGREEN_HEX COLOR_DARKJUNGLEGREEN_R << 16 | COLOR_DARKJUNGLEGREEN_G  << 8 | COLOR_DARKJUNGLEGREEN_B


#define COLOR_DARKKHAKI_R 189
#define COLOR_DARKKHAKI_G 183
#define COLOR_DARKKHAKI_B 107
#define COLOR_DARKKHAKI_HEX COLOR_DARKKHAKI_R << 16 | COLOR_DARKKHAKI_G  << 8 | COLOR_DARKKHAKI_B


#define COLOR_DARKMAGENTA_R 139
#define COLOR_DARKMAGENTA_G 0
#define COLOR_DARKMAGENTA_B 139
#define COLOR_DARKMAGENTA_HEX COLOR_DARKMAGENTA_R << 16 | COLOR_DARKMAGENTA_G  << 8 | COLOR_DARKMAGENTA_B


#define COLOR_DARKMAROON_R 113
#define COLOR_DARKMAROON_G 12
#define COLOR_DARKMAROON_B 4
#define COLOR_DARKMAROON_HEX COLOR_DARKMAROON_R << 16 | COLOR_DARKMAROON_G  << 8 | COLOR_DARKMAROON_B


#define COLOR_DARKMULBERRY_R 76
#define COLOR_DARKMULBERRY_G 1
#define COLOR_DARKMULBERRY_B 33
#define COLOR_DARKMULBERRY_HEX COLOR_DARKMULBERRY_R << 16 | COLOR_DARKMULBERRY_G  << 8 | COLOR_DARKMULBERRY_B


#define COLOR_DARKNAVY_R 10
#define COLOR_DARKNAVY_G 17
#define COLOR_DARKNAVY_B 114
#define COLOR_DARKNAVY_HEX COLOR_DARKNAVY_R << 16 | COLOR_DARKNAVY_G  << 8 | COLOR_DARKNAVY_B


#define COLOR_DARKORANGE_R 255
#define COLOR_DARKORANGE_G 140
#define COLOR_DARKORANGE_B 0
#define COLOR_DARKORANGE_HEX COLOR_DARKORANGE_R << 16 | COLOR_DARKORANGE_G  << 8 | COLOR_DARKORANGE_B


#define COLOR_DARKORCHID_R 153
#define COLOR_DARKORCHID_G 50
#define COLOR_DARKORCHID_B 204
#define COLOR_DARKORCHID_HEX COLOR_DARKORCHID_R << 16 | COLOR_DARKORCHID_G  << 8 | COLOR_DARKORCHID_B


#define COLOR_DARKPINK_R 231
#define COLOR_DARKPINK_G 84
#define COLOR_DARKPINK_B 128
#define COLOR_DARKPINK_HEX COLOR_DARKPINK_R << 16 | COLOR_DARKPINK_G  << 8 | COLOR_DARKPINK_B


#define COLOR_DARKPURPLE_R 48
#define COLOR_DARKPURPLE_G 25
#define COLOR_DARKPURPLE_B 52
#define COLOR_DARKPURPLE_HEX COLOR_DARKPURPLE_R << 16 | COLOR_DARKPURPLE_G  << 8 | COLOR_DARKPURPLE_B


#define COLOR_DARKRED_R 139
#define COLOR_DARKRED_G 0
#define COLOR_DARKRED_B 0
#define COLOR_DARKRED_HEX COLOR_DARKRED_R << 16 | COLOR_DARKRED_G  << 8 | COLOR_DARKRED_B


#define COLOR_DARKSALMON_R 233
#define COLOR_DARKSALMON_G 150
#define COLOR_DARKSALMON_B 122
#define COLOR_DARKSALMON_HEX COLOR_DARKSALMON_R << 16 | COLOR_DARKSALMON_G  << 8 | COLOR_DARKSALMON_B


#define COLOR_DARKSEAGREEN_R 143
#define COLOR_DARKSEAGREEN_G 188
#define COLOR_DARKSEAGREEN_B 143
#define COLOR_DARKSEAGREEN_HEX COLOR_DARKSEAGREEN_R << 16 | COLOR_DARKSEAGREEN_G  << 8 | COLOR_DARKSEAGREEN_B


#define COLOR_DARKSLATE_R 62
#define COLOR_DARKSLATE_G 61
#define COLOR_DARKSLATE_B 83
#define COLOR_DARKSLATE_HEX COLOR_DARKSLATE_R << 16 | COLOR_DARKSLATE_G  << 8 | COLOR_DARKSLATE_B


#define COLOR_DARKSLATEBLUE_R 72
#define COLOR_DARKSLATEBLUE_G 61
#define COLOR_DARKSLATEBLUE_B 139
#define COLOR_DARKSLATEBLUE_HEX COLOR_DARKSLATEBLUE_R << 16 | COLOR_DARKSLATEBLUE_G  << 8 | COLOR_DARKSLATEBLUE_B


#define COLOR_DARKSLATEGRAY_R 47
#define COLOR_DARKSLATEGRAY_G 79
#define COLOR_DARKSLATEGRAY_B 79
#define COLOR_DARKSLATEGRAY_HEX COLOR_DARKSLATEGRAY_R << 16 | COLOR_DARKSLATEGRAY_G  << 8 | COLOR_DARKSLATEGRAY_B


#define COLOR_DARKTURQUOISE_R 0
#define COLOR_DARKTURQUOISE_G 206
#define COLOR_DARKTURQUOISE_B 209
#define COLOR_DARKTURQUOISE_HEX COLOR_DARKTURQUOISE_R << 16 | COLOR_DARKTURQUOISE_G  << 8 | COLOR_DARKTURQUOISE_B


#define COLOR_DARKVIOLET_R 113
#define COLOR_DARKVIOLET_G 1
#define COLOR_DARKVIOLET_B 147
#define COLOR_DARKVIOLET_HEX COLOR_DARKVIOLET_R << 16 | COLOR_DARKVIOLET_G  << 8 | COLOR_DARKVIOLET_B


#define COLOR_DAVYSGRAY_R 85
#define COLOR_DAVYSGRAY_G 85
#define COLOR_DAVYSGRAY_B 85
#define COLOR_DAVYSGRAY_HEX COLOR_DAVYSGRAY_R << 16 | COLOR_DAVYSGRAY_G  << 8 | COLOR_DAVYSGRAY_B


#define COLOR_DAYGREY_R 135
#define COLOR_DAYGREY_G 135
#define COLOR_DAYGREY_B 135
#define COLOR_DAYGREY_HEX COLOR_DAYGREY_R << 16 | COLOR_DAYGREY_G  << 8 | COLOR_DAYGREY_B


#define COLOR_DEEPCOFFEE_R 112
#define COLOR_DEEPCOFFEE_G 66
#define COLOR_DEEPCOFFEE_B 65
#define COLOR_DEEPCOFFEE_HEX COLOR_DEEPCOFFEE_R << 16 | COLOR_DEEPCOFFEE_G  << 8 | COLOR_DEEPCOFFEE_B


#define COLOR_DEEPLILAC_R 182
#define COLOR_DEEPLILAC_G 95
#define COLOR_DEEPLILAC_B 207
#define COLOR_DEEPLILAC_HEX COLOR_DEEPLILAC_R << 16 | COLOR_DEEPLILAC_G  << 8 | COLOR_DEEPLILAC_B


#define COLOR_DEEPPINK_R 255
#define COLOR_DEEPPINK_G 20
#define COLOR_DEEPPINK_B 147
#define COLOR_DEEPPINK_HEX COLOR_DEEPPINK_R << 16 | COLOR_DEEPPINK_G  << 8 | COLOR_DEEPPINK_B


#define COLOR_DEEPSAFFRON_R 255
#define COLOR_DEEPSAFFRON_G 165
#define COLOR_DEEPSAFFRON_B 44
#define COLOR_DEEPSAFFRON_HEX COLOR_DEEPSAFFRON_R << 16 | COLOR_DEEPSAFFRON_G  << 8 | COLOR_DEEPSAFFRON_B


#define COLOR_DEEPSKYBLUE_R 0
#define COLOR_DEEPSKYBLUE_G 191
#define COLOR_DEEPSKYBLUE_B 255
#define COLOR_DEEPSKYBLUE_HEX COLOR_DEEPSKYBLUE_R << 16 | COLOR_DEEPSKYBLUE_G  << 8 | COLOR_DEEPSKYBLUE_B


#define COLOR_DEEPWINE_R 44
#define COLOR_DEEPWINE_G 4
#define COLOR_DEEPWINE_B 28
#define COLOR_DEEPWINE_HEX COLOR_DEEPWINE_R << 16 | COLOR_DEEPWINE_G  << 8 | COLOR_DEEPWINE_B


#define COLOR_DENIM_R 21
#define COLOR_DENIM_G 30
#define COLOR_DENIM_B 61
#define COLOR_DENIM_HEX COLOR_DENIM_R << 16 | COLOR_DENIM_G  << 8 | COLOR_DENIM_B


#define COLOR_DESIRE_R 234
#define COLOR_DESIRE_G 60
#define COLOR_DESIRE_B 83
#define COLOR_DESIRE_HEX COLOR_DESIRE_R << 16 | COLOR_DESIRE_G  << 8 | COLOR_DESIRE_B


#define COLOR_DIMGRAY_R 105
#define COLOR_DIMGRAY_G 105
#define COLOR_DIMGRAY_B 105
#define COLOR_DIMGRAY_HEX COLOR_DIMGRAY_R << 16 | COLOR_DIMGRAY_G  << 8 | COLOR_DIMGRAY_B


#define COLOR_DODGERBLUE_R 30
#define COLOR_DODGERBLUE_G 144
#define COLOR_DODGERBLUE_B 255
#define COLOR_DODGERBLUE_HEX COLOR_DODGERBLUE_R << 16 | COLOR_DODGERBLUE_G  << 8 | COLOR_DODGERBLUE_B


#define COLOR_DOVE_R 124
#define COLOR_DOVE_G 110
#define COLOR_DOVE_B 127
#define COLOR_DOVE_HEX COLOR_DOVE_R << 16 | COLOR_DOVE_G  << 8 | COLOR_DOVE_B


#define COLOR_EBONY_R 8
#define COLOR_EBONY_G 4
#define COLOR_EBONY_B 2
#define COLOR_EBONY_HEX COLOR_EBONY_R << 16 | COLOR_EBONY_G  << 8 | COLOR_EBONY_B


#define COLOR_ECRU_R 194
#define COLOR_ECRU_G 178
#define COLOR_ECRU_B 128
#define COLOR_ECRU_HEX COLOR_ECRU_R << 16 | COLOR_ECRU_G  << 8 | COLOR_ECRU_B


#define COLOR_EERIEBLACK_R 27
#define COLOR_EERIEBLACK_G 27
#define COLOR_EERIEBLACK_B 27
#define COLOR_EERIEBLACK_HEX COLOR_EERIEBLACK_R << 16 | COLOR_EERIEBLACK_G  << 8 | COLOR_EERIEBLACK_B


#define COLOR_EGGNOG_R 250
#define COLOR_EGGNOG_G 226
#define COLOR_EGGNOG_B 156
#define COLOR_EGGNOG_HEX COLOR_EGGNOG_R << 16 | COLOR_EGGNOG_G  << 8 | COLOR_EGGNOG_B


#define COLOR_EGGPLANT_R 49
#define COLOR_EGGPLANT_G 20
#define COLOR_EGGPLANT_B 50
#define COLOR_EGGPLANT_HEX COLOR_EGGPLANT_R << 16 | COLOR_EGGPLANT_G  << 8 | COLOR_EGGPLANT_B


#define COLOR_EGGSHELL_R 255
#define COLOR_EGGSHELL_G 249
#define COLOR_EGGSHELL_B 227
#define COLOR_EGGSHELL_HEX COLOR_EGGSHELL_R << 16 | COLOR_EGGSHELL_G  << 8 | COLOR_EGGSHELL_B


#define COLOR_EGYPTIANBLUE_R 16
#define COLOR_EGYPTIANBLUE_G 52
#define COLOR_EGYPTIANBLUE_B 166
#define COLOR_EGYPTIANBLUE_HEX COLOR_EGYPTIANBLUE_R << 16 | COLOR_EGYPTIANBLUE_G  << 8 | COLOR_EGYPTIANBLUE_B


#define COLOR_ELECTRICLAVENDER_R 227
#define COLOR_ELECTRICLAVENDER_G 159
#define COLOR_ELECTRICLAVENDER_B 246
#define COLOR_ELECTRICLAVENDER_HEX COLOR_ELECTRICLAVENDER_R << 16 | COLOR_ELECTRICLAVENDER_G  << 8 | COLOR_ELECTRICLAVENDER_B


#define COLOR_EMERALD_R 2
#define COLOR_EMERALD_G 138
#define COLOR_EMERALD_B 15
#define COLOR_EMERALD_HEX COLOR_EMERALD_R << 16 | COLOR_EMERALD_G  << 8 | COLOR_EMERALD_B


#define COLOR_EMINENCE_R 108
#define COLOR_EMINENCE_G 48
#define COLOR_EMINENCE_B 130
#define COLOR_EMINENCE_HEX COLOR_EMINENCE_R << 16 | COLOR_EMINENCE_G  << 8 | COLOR_EMINENCE_B


#define COLOR_ENGLISHVIOLET_R 86
#define COLOR_ENGLISHVIOLET_G 60
#define COLOR_ENGLISHVIOLET_B 92
#define COLOR_ENGLISHVIOLET_HEX COLOR_ENGLISHVIOLET_R << 16 | COLOR_ENGLISHVIOLET_G  << 8 | COLOR_ENGLISHVIOLET_B


#define COLOR_FAWN_R 200
#define COLOR_FAWN_G 169
#define COLOR_FAWN_B 81
#define COLOR_FAWN_HEX COLOR_FAWN_R << 16 | COLOR_FAWN_G  << 8 | COLOR_FAWN_B


#define COLOR_FERN_R 93
#define COLOR_FERN_G 187
#define COLOR_FERN_B 99
#define COLOR_FERN_HEX COLOR_FERN_R << 16 | COLOR_FERN_G  << 8 | COLOR_FERN_B


#define COLOR_FERRARI_R 255
#define COLOR_FERRARI_G 40
#define COLOR_FERRARI_B 0
#define COLOR_FERRARI_HEX COLOR_FERRARI_R << 16 | COLOR_FERRARI_G  << 8 | COLOR_FERRARI_B


#define COLOR_FIRE_R 221
#define COLOR_FIRE_G 87
#define COLOR_FIRE_B 28
#define COLOR_FIRE_HEX COLOR_FIRE_R << 16 | COLOR_FIRE_G  << 8 | COLOR_FIRE_B


#define COLOR_FIREBRICK_R 178
#define COLOR_FIREBRICK_G 34
#define COLOR_FIREBRICK_B 34
#define COLOR_FIREBRICK_HEX COLOR_FIREBRICK_R << 16 | COLOR_FIREBRICK_G  << 8 | COLOR_FIREBRICK_B


#define COLOR_FLAME_R 227
#define COLOR_FLAME_G 74
#define COLOR_FLAME_B 39
#define COLOR_FLAME_HEX COLOR_FLAME_R << 16 | COLOR_FLAME_G  << 8 | COLOR_FLAME_B


#define COLOR_FLAMINGO_R 253
#define COLOR_FLAMINGO_G 164
#define COLOR_FLAMINGO_B 186
#define COLOR_FLAMINGO_HEX COLOR_FLAMINGO_R << 16 | COLOR_FLAMINGO_G  << 8 | COLOR_FLAMINGO_B


#define COLOR_FLAX_R 238
#define COLOR_FLAX_G 220
#define COLOR_FLAX_B 130
#define COLOR_FLAX_HEX COLOR_FLAX_R << 16 | COLOR_FLAX_G  << 8 | COLOR_FLAX_B


#define COLOR_FLINT_R 127
#define COLOR_FLINT_G 125
#define COLOR_FLINT_B 156
#define COLOR_FLINT_HEX COLOR_FLINT_R << 16 | COLOR_FLINT_G  << 8 | COLOR_FLINT_B


#define COLOR_FLORALWHITE_R 255
#define COLOR_FLORALWHITE_G 250
#define COLOR_FLORALWHITE_B 240
#define COLOR_FLORALWHITE_HEX COLOR_FLORALWHITE_R << 16 | COLOR_FLORALWHITE_G  << 8 | COLOR_FLORALWHITE_B


#define COLOR_FOG_R 101
#define COLOR_FOG_G 89
#define COLOR_FOG_B 103
#define COLOR_FOG_HEX COLOR_FOG_R << 16 | COLOR_FOG_G  << 8 | COLOR_FOG_B


#define COLOR_FORESTGREEN_R 11
#define COLOR_FORESTGREEN_G 102
#define COLOR_FORESTGREEN_B 35
#define COLOR_FORESTGREEN_HEX COLOR_FORESTGREEN_R << 16 | COLOR_FORESTGREEN_G  << 8 | COLOR_FORESTGREEN_B


#define COLOR_FOSSIL_R 120
#define COLOR_FOSSIL_G 114
#define COLOR_FOSSIL_B 118
#define COLOR_FOSSIL_HEX COLOR_FOSSIL_R << 16 | COLOR_FOSSIL_G  << 8 | COLOR_FOSSIL_B


#define COLOR_FRENCHFUCHSIA_R 252
#define COLOR_FRENCHFUCHSIA_G 70
#define COLOR_FRENCHFUCHSIA_B 170
#define COLOR_FRENCHFUCHSIA_HEX COLOR_FRENCHFUCHSIA_R << 16 | COLOR_FRENCHFUCHSIA_G  << 8 | COLOR_FRENCHFUCHSIA_B


#define COLOR_FRENCHPINK_R 246
#define COLOR_FRENCHPINK_G 74
#define COLOR_FRENCHPINK_B 138
#define COLOR_FRENCHPINK_HEX COLOR_FRENCHPINK_R << 16 | COLOR_FRENCHPINK_G  << 8 | COLOR_FRENCHPINK_B


#define COLOR_FROST_R 236
#define COLOR_FROST_G 251
#define COLOR_FROST_B 252
#define COLOR_FROST_HEX COLOR_FROST_R << 16 | COLOR_FROST_G  << 8 | COLOR_FROST_B


#define COLOR_FROSTBLACK_R 25
#define COLOR_FROSTBLACK_G 28
#define COLOR_FROSTBLACK_B 32
#define COLOR_FROSTBLACK_HEX COLOR_FROSTBLACK_R << 16 | COLOR_FROSTBLACK_G  << 8 | COLOR_FROSTBLACK_B


#define COLOR_FUCHSIA_R 255
#define COLOR_FUCHSIA_G 0
#define COLOR_FUCHSIA_B 255
#define COLOR_FUCHSIA_HEX COLOR_FUCHSIA_R << 16 | COLOR_FUCHSIA_G  << 8 | COLOR_FUCHSIA_B


#define COLOR_FULVOUS_R 230
#define COLOR_FULVOUS_G 128
#define COLOR_FULVOUS_B 0
#define COLOR_FULVOUS_HEX COLOR_FULVOUS_R << 16 | COLOR_FULVOUS_G  << 8 | COLOR_FULVOUS_B


#define COLOR_GAINSBORO_R 220
#define COLOR_GAINSBORO_G 220
#define COLOR_GAINSBORO_B 220
#define COLOR_GAINSBORO_HEX COLOR_GAINSBORO_R << 16 | COLOR_GAINSBORO_G  << 8 | COLOR_GAINSBORO_B


#define COLOR_GAMBOGE_R 232
#define COLOR_GAMBOGE_G 150
#define COLOR_GAMBOGE_B 17
#define COLOR_GAMBOGE_HEX COLOR_GAMBOGE_R << 16 | COLOR_GAMBOGE_G  << 8 | COLOR_GAMBOGE_B


#define COLOR_GARNET_R 97
#define COLOR_GARNET_G 12
#define COLOR_GARNET_B 4
#define COLOR_GARNET_HEX COLOR_GARNET_R << 16 | COLOR_GARNET_G  << 8 | COLOR_GARNET_B


#define COLOR_GHOSTWHITE_R 248
#define COLOR_GHOSTWHITE_G 248
#define COLOR_GHOSTWHITE_B 255
#define COLOR_GHOSTWHITE_HEX COLOR_GHOSTWHITE_R << 16 | COLOR_GHOSTWHITE_G  << 8 | COLOR_GHOSTWHITE_B


#define COLOR_GINGER_R 190
#define COLOR_GINGER_G 85
#define COLOR_GINGER_B 4
#define COLOR_GINGER_HEX COLOR_GINGER_R << 16 | COLOR_GINGER_G  << 8 | COLOR_GINGER_B


#define COLOR_GINGERBREAD_R 94
#define COLOR_GINGERBREAD_G 44
#define COLOR_GINGERBREAD_B 4
#define COLOR_GINGERBREAD_HEX COLOR_GINGERBREAD_R << 16 | COLOR_GINGERBREAD_G  << 8 | COLOR_GINGERBREAD_B


#define COLOR_GOLD_R 255
#define COLOR_GOLD_G 215
#define COLOR_GOLD_B 0
#define COLOR_GOLD_HEX COLOR_GOLD_R << 16 | COLOR_GOLD_G  << 8 | COLOR_GOLD_B


#define COLOR_GOLDENBROWN_R 153
#define COLOR_GOLDENBROWN_G 101
#define COLOR_GOLDENBROWN_B 21
#define COLOR_GOLDENBROWN_HEX COLOR_GOLDENBROWN_R << 16 | COLOR_GOLDENBROWN_G  << 8 | COLOR_GOLDENBROWN_B


#define COLOR_GOLDENROD_R 218
#define COLOR_GOLDENROD_G 165
#define COLOR_GOLDENROD_B 32
#define COLOR_GOLDENROD_HEX COLOR_GOLDENROD_R << 16 | COLOR_GOLDENROD_G  << 8 | COLOR_GOLDENROD_B


#define COLOR_GOTHICGRAPE_R 18
#define COLOR_GOTHICGRAPE_G 3
#define COLOR_GOTHICGRAPE_B 33
#define COLOR_GOTHICGRAPE_HEX COLOR_GOTHICGRAPE_R << 16 | COLOR_GOTHICGRAPE_G  << 8 | COLOR_GOTHICGRAPE_B


#define COLOR_GRANOLA_R 214
#define COLOR_GRANOLA_G 184
#define COLOR_GRANOLA_B 90
#define COLOR_GRANOLA_HEX COLOR_GRANOLA_R << 16 | COLOR_GRANOLA_G  << 8 | COLOR_GRANOLA_B


#define COLOR_GRAPE_R 102
#define COLOR_GRAPE_G 48
#define COLOR_GRAPE_B 70
#define COLOR_GRAPE_HEX COLOR_GRAPE_R << 16 | COLOR_GRAPE_G  << 8 | COLOR_GRAPE_B


#define COLOR_GRAPHITE_R 89
#define COLOR_GRAPHITE_G 77
#define COLOR_GRAPHITE_B 91
#define COLOR_GRAPHITE_HEX COLOR_GRAPHITE_R << 16 | COLOR_GRAPHITE_G  << 8 | COLOR_GRAPHITE_B


#define COLOR_GRAY_R 128
#define COLOR_GRAY_G 128
#define COLOR_GRAY_B 128
#define COLOR_GRAY_HEX COLOR_GRAY_R << 16 | COLOR_GRAY_G  << 8 | COLOR_GRAY_B


#define COLOR_GRAYCLOUD_R 182
#define COLOR_GRAYCLOUD_G 182
#define COLOR_GRAYCLOUD_B 180
#define COLOR_GRAYCLOUD_HEX COLOR_GRAYCLOUD_R << 16 | COLOR_GRAYCLOUD_G  << 8 | COLOR_GRAYCLOUD_B


#define COLOR_GRAYDOLPHIN_R 92
#define COLOR_GRAYDOLPHIN_G 88
#define COLOR_GRAYDOLPHIN_B 88
#define COLOR_GRAYDOLPHIN_HEX COLOR_GRAYDOLPHIN_R << 16 | COLOR_GRAYDOLPHIN_G  << 8 | COLOR_GRAYDOLPHIN_B


#define COLOR_GRAYWOLF_R 80
#define COLOR_GRAYWOLF_G 74
#define COLOR_GRAYWOLF_B 75
#define COLOR_GRAYWOLF_HEX COLOR_GRAYWOLF_R << 16 | COLOR_GRAYWOLF_G  << 8 | COLOR_GRAYWOLF_B


#define COLOR_GREASE_R 10
#define COLOR_GREASE_G 8
#define COLOR_GREASE_B 6
#define COLOR_GREASE_HEX COLOR_GREASE_R << 16 | COLOR_GREASE_G  << 8 | COLOR_GREASE_B


#define COLOR_GREEN_R 0
#define COLOR_GREEN_G 255
#define COLOR_GREEN_B 0
#define COLOR_GREEN_HEX COLOR_GREEN_R << 16 | COLOR_GREEN_G  << 8 | COLOR_GREEN_B


#define COLOR_GREENGREY_R 60
#define COLOR_GREENGREY_G 176
#define COLOR_GREENGREY_B 67
#define COLOR_GREENGREY_HEX COLOR_GREENGREY_R << 16 | COLOR_GREENGREY_G  << 8 | COLOR_GREENGREY_B


#define COLOR_GREENISHYELLOW_R 238
#define COLOR_GREENISHYELLOW_G 234
#define COLOR_GREENISHYELLOW_B 98
#define COLOR_GREENISHYELLOW_HEX COLOR_GREENISHYELLOW_R << 16 | COLOR_GREENISHYELLOW_G  << 8 | COLOR_GREENISHYELLOW_B


#define COLOR_GUNMETAL_R 42
#define COLOR_GUNMETAL_G 52
#define COLOR_GUNMETAL_B 57
#define COLOR_GUNMETAL_HEX COLOR_GUNMETAL_R << 16 | COLOR_GUNMETAL_G  << 8 | COLOR_GUNMETAL_B


#define COLOR_HALLOWEENORANGE_R 238
#define COLOR_HALLOWEENORANGE_G 89
#define COLOR_HALLOWEENORANGE_B 33
#define COLOR_HALLOWEENORANGE_HEX COLOR_HALLOWEENORANGE_R << 16 | COLOR_HALLOWEENORANGE_G  << 8 | COLOR_HALLOWEENORANGE_B


#define COLOR_HARP_R 235
#define COLOR_HARP_G 245
#define COLOR_HARP_B 240
#define COLOR_HARP_HEX COLOR_HARP_R << 16 | COLOR_HARP_G  << 8 | COLOR_HARP_B


#define COLOR_HAZELNUT_R 189
#define COLOR_HAZELNUT_G 165
#define COLOR_HAZELNUT_B 93
#define COLOR_HAZELNUT_HEX COLOR_HAZELNUT_R << 16 | COLOR_HAZELNUT_G  << 8 | COLOR_HAZELNUT_B


#define COLOR_HAZELWOOD_R 201
#define COLOR_HAZELWOOD_G 187
#define COLOR_HAZELWOOD_B 142
#define COLOR_HAZELWOOD_HEX COLOR_HAZELWOOD_R << 16 | COLOR_HAZELWOOD_G  << 8 | COLOR_HAZELWOOD_B


#define COLOR_HEATHER_R 158
#define COLOR_HEATHER_G 123
#define COLOR_HEATHER_B 181
#define COLOR_HEATHER_HEX COLOR_HEATHER_R << 16 | COLOR_HEATHER_G  << 8 | COLOR_HEATHER_B


#define COLOR_HELIOTROPE_R 223
#define COLOR_HELIOTROPE_G 115
#define COLOR_HELIOTROPE_B 255
#define COLOR_HELIOTROPE_HEX COLOR_HELIOTROPE_R << 16 | COLOR_HELIOTROPE_G  << 8 | COLOR_HELIOTROPE_B


#define COLOR_HIBISCUS_R 180
#define COLOR_HIBISCUS_G 55
#define COLOR_HIBISCUS_B 87
#define COLOR_HIBISCUS_HEX COLOR_HIBISCUS_R << 16 | COLOR_HIBISCUS_G  << 8 | COLOR_HIBISCUS_B


#define COLOR_HICKORY_R 55
#define COLOR_HICKORY_G 29
#define COLOR_HICKORY_B 16
#define COLOR_HICKORY_HEX COLOR_HICKORY_R << 16 | COLOR_HICKORY_G  << 8 | COLOR_HICKORY_B


#define COLOR_HONEY_R 236
#define COLOR_HONEY_G 151
#define COLOR_HONEY_B 6
#define COLOR_HONEY_HEX COLOR_HONEY_R << 16 | COLOR_HONEY_G  << 8 | COLOR_HONEY_B


#define COLOR_HONEYDEW_R 240
#define COLOR_HONEYDEW_G 255
#define COLOR_HONEYDEW_B 240
#define COLOR_HONEYDEW_HEX COLOR_HONEYDEW_R << 16 | COLOR_HONEYDEW_G  << 8 | COLOR_HONEYDEW_B


#define COLOR_HOTPINK_R 255
#define COLOR_HOTPINK_G 105
#define COLOR_HOTPINK_B 180
#define COLOR_HOTPINK_HEX COLOR_HOTPINK_R << 16 | COLOR_HOTPINK_G  << 8 | COLOR_HOTPINK_B


#define COLOR_HUNTERGREEN_R 63
#define COLOR_HUNTERGREEN_G 112
#define COLOR_HUNTERGREEN_B 77
#define COLOR_HUNTERGREEN_HEX COLOR_HUNTERGREEN_R << 16 | COLOR_HUNTERGREEN_G  << 8 | COLOR_HUNTERGREEN_B


#define COLOR_IMPERIALBLUE_R 0
#define COLOR_IMPERIALBLUE_G 90
#define COLOR_IMPERIALBLUE_B 146
#define COLOR_IMPERIALBLUE_HEX COLOR_IMPERIALBLUE_R << 16 | COLOR_IMPERIALBLUE_G  << 8 | COLOR_IMPERIALBLUE_B


#define COLOR_IMPERIALRED_R 237
#define COLOR_IMPERIALRED_G 41
#define COLOR_IMPERIALRED_B 57
#define COLOR_IMPERIALRED_HEX COLOR_IMPERIALRED_R << 16 | COLOR_IMPERIALRED_G  << 8 | COLOR_IMPERIALRED_B


#define COLOR_INDIANRED_R 205
#define COLOR_INDIANRED_G 92
#define COLOR_INDIANRED_B 92
#define COLOR_INDIANRED_HEX COLOR_INDIANRED_R << 16 | COLOR_INDIANRED_G  << 8 | COLOR_INDIANRED_B


#define COLOR_INDIGO_R 75
#define COLOR_INDIGO_G 0
#define COLOR_INDIGO_B 130
#define COLOR_INDIGO_HEX COLOR_INDIGO_R << 16 | COLOR_INDIGO_G  << 8 | COLOR_INDIGO_B


#define COLOR_INK_R 7
#define COLOR_INK_G 5
#define COLOR_INK_B 4
#define COLOR_INK_HEX COLOR_INK_R << 16 | COLOR_INK_G  << 8 | COLOR_INK_B


#define COLOR_INTERNATIONALORANGE_R 255
#define COLOR_INTERNATIONALORANGE_G 79
#define COLOR_INTERNATIONALORANGE_B 0
#define COLOR_INTERNATIONALORANGE_HEX COLOR_INTERNATIONALORANGE_R << 16 | COLOR_INTERNATIONALORANGE_G  << 8 | COLOR_INTERNATIONALORANGE_B


#define COLOR_IRIS_R 152
#define COLOR_IRIS_G 103
#define COLOR_IRIS_B 197
#define COLOR_IRIS_HEX COLOR_IRIS_R << 16 | COLOR_IRIS_G  << 8 | COLOR_IRIS_B


#define COLOR_IRON_R 50
#define COLOR_IRON_G 45
#define COLOR_IRON_B 49
#define COLOR_IRON_HEX COLOR_IRON_R << 16 | COLOR_IRON_G  << 8 | COLOR_IRON_B


#define COLOR_ISLANDSPICE_R 255
#define COLOR_ISLANDSPICE_G 252
#define COLOR_ISLANDSPICE_B 236
#define COLOR_ISLANDSPICE_HEX COLOR_ISLANDSPICE_R << 16 | COLOR_ISLANDSPICE_G  << 8 | COLOR_ISLANDSPICE_B


#define COLOR_IVORY_R 255
#define COLOR_IVORY_G 255
#define COLOR_IVORY_B 240
#define COLOR_IVORY_HEX COLOR_IVORY_R << 16 | COLOR_IVORY_G  << 8 | COLOR_IVORY_B


#define COLOR_JADE_R 0
#define COLOR_JADE_G 168
#define COLOR_JADE_B 107
#define COLOR_JADE_HEX COLOR_JADE_R << 16 | COLOR_JADE_G  << 8 | COLOR_JADE_B


#define COLOR_JAM_R 96
#define COLOR_JAM_G 16
#define COLOR_JAM_B 11
#define COLOR_JAM_HEX COLOR_JAM_R << 16 | COLOR_JAM_G  << 8 | COLOR_JAM_B


#define COLOR_JAZZBERRYJAM_R 103
#define COLOR_JAZZBERRYJAM_G 3
#define COLOR_JAZZBERRYJAM_B 47
#define COLOR_JAZZBERRYJAM_HEX COLOR_JAZZBERRYJAM_R << 16 | COLOR_JAZZBERRYJAM_G  << 8 | COLOR_JAZZBERRYJAM_B


#define COLOR_JETBLACK_R 3
#define COLOR_JETBLACK_G 3
#define COLOR_JETBLACK_B 3
#define COLOR_JETBLACK_HEX COLOR_JETBLACK_R << 16 | COLOR_JETBLACK_G  << 8 | COLOR_JETBLACK_B


#define COLOR_JUNGLEGREEN_R 41
#define COLOR_JUNGLEGREEN_G 171
#define COLOR_JUNGLEGREEN_B 135
#define COLOR_JUNGLEGREEN_HEX COLOR_JUNGLEGREEN_R << 16 | COLOR_JUNGLEGREEN_G  << 8 | COLOR_JUNGLEGREEN_B


#define COLOR_JUNIPER_R 58
#define COLOR_JUNIPER_G 83
#define COLOR_JUNIPER_B 17
#define COLOR_JUNIPER_HEX COLOR_JUNIPER_R << 16 | COLOR_JUNIPER_G  << 8 | COLOR_JUNIPER_B


#define COLOR_KELLYGREEN_R 76
#define COLOR_KELLYGREEN_G 187
#define COLOR_KELLYGREEN_B 23
#define COLOR_KELLYGREEN_HEX COLOR_KELLYGREEN_R << 16 | COLOR_KELLYGREEN_G  << 8 | COLOR_KELLYGREEN_B


#define COLOR_KHAKI_R 240
#define COLOR_KHAKI_G 230
#define COLOR_KHAKI_B 140
#define COLOR_KHAKI_HEX COLOR_KHAKI_R << 16 | COLOR_KHAKI_G  << 8 | COLOR_KHAKI_B


#define COLOR_KHAKIBROWN_R 195
#define COLOR_KHAKIBROWN_G 176
#define COLOR_KHAKIBROWN_B 145
#define COLOR_KHAKIBROWN_HEX COLOR_KHAKIBROWN_R << 16 | COLOR_KHAKIBROWN_G  << 8 | COLOR_KHAKIBROWN_B


#define COLOR_KSUPURPLE_R 81
#define COLOR_KSUPURPLE_G 40
#define COLOR_KSUPURPLE_B 136
#define COLOR_KSUPURPLE_HEX COLOR_KSUPURPLE_R << 16 | COLOR_KSUPURPLE_G  << 8 | COLOR_KSUPURPLE_B


#define COLOR_LACE_R 248
#define COLOR_LACE_G 242
#define COLOR_LACE_B 237
#define COLOR_LACE_HEX COLOR_LACE_R << 16 | COLOR_LACE_G  << 8 | COLOR_LACE_B


#define COLOR_LAGUNA_R 248
#define COLOR_LAGUNA_G 228
#define COLOR_LAGUNA_B 115
#define COLOR_LAGUNA_HEX COLOR_LAGUNA_R << 16 | COLOR_LAGUNA_G  << 8 | COLOR_LAGUNA_B


#define COLOR_LAPIS_R 38
#define COLOR_LAPIS_G 97
#define COLOR_LAPIS_B 156
#define COLOR_LAPIS_HEX COLOR_LAPIS_R << 16 | COLOR_LAPIS_G  << 8 | COLOR_LAPIS_B


#define COLOR_LATTE_R 231
#define COLOR_LATTE_G 194
#define COLOR_LATTE_B 125
#define COLOR_LATTE_HEX COLOR_LATTE_R << 16 | COLOR_LATTE_G  << 8 | COLOR_LATTE_B


#define COLOR_LAURELGREEN_R 169
#define COLOR_LAURELGREEN_G 186
#define COLOR_LAURELGREEN_B 157
#define COLOR_LAURELGREEN_HEX COLOR_LAURELGREEN_R << 16 | COLOR_LAURELGREEN_G  << 8 | COLOR_LAURELGREEN_B


#define COLOR_LAVENDER_R 230
#define COLOR_LAVENDER_G 230
#define COLOR_LAVENDER_B 250
#define COLOR_LAVENDER_HEX COLOR_LAVENDER_R << 16 | COLOR_LAVENDER_G  << 8 | COLOR_LAVENDER_B


#define COLOR_LAVENDERBLUSH_R 255
#define COLOR_LAVENDERBLUSH_G 240
#define COLOR_LAVENDERBLUSH_B 245
#define COLOR_LAVENDERBLUSH_HEX COLOR_LAVENDERBLUSH_R << 16 | COLOR_LAVENDERBLUSH_G  << 8 | COLOR_LAVENDERBLUSH_B


#define COLOR_LAWNGREEN_R 124
#define COLOR_LAWNGREEN_G 252
#define COLOR_LAWNGREEN_B 0
#define COLOR_LAWNGREEN_HEX COLOR_LAWNGREEN_R << 16 | COLOR_LAWNGREEN_G  << 8 | COLOR_LAWNGREEN_B


#define COLOR_LEAD_R 63
#define COLOR_LEAD_G 63
#define COLOR_LEAD_B 78
#define COLOR_LEAD_HEX COLOR_LEAD_R << 16 | COLOR_LEAD_G  << 8 | COLOR_LEAD_B


#define COLOR_LEATHER_R 11
#define COLOR_LEATHER_G 7
#define COLOR_LEATHER_B 5
#define COLOR_LEATHER_HEX COLOR_LEATHER_R << 16 | COLOR_LEATHER_G  << 8 | COLOR_LEATHER_B


#define COLOR_LEMONADE_R 252
#define COLOR_LEMONADE_G 186
#define COLOR_LEMONADE_B 203
#define COLOR_LEMONADE_HEX COLOR_LEMONADE_R << 16 | COLOR_LEMONADE_G  << 8 | COLOR_LEMONADE_B


#define COLOR_LEMONADECREPE_R 242
#define COLOR_LEMONADECREPE_G 184
#define COLOR_LEMONADECREPE_B 198
#define COLOR_LEMONADECREPE_HEX COLOR_LEMONADECREPE_R << 16 | COLOR_LEMONADECREPE_G  << 8 | COLOR_LEMONADECREPE_B


#define COLOR_LEMONCHIFFON_R 255
#define COLOR_LEMONCHIFFON_G 250
#define COLOR_LEMONCHIFFON_B 205
#define COLOR_LEMONCHIFFON_HEX COLOR_LEMONCHIFFON_R << 16 | COLOR_LEMONCHIFFON_G  << 8 | COLOR_LEMONCHIFFON_B


#define COLOR_LEMONLIME_R 174
#define COLOR_LEMONLIME_G 243
#define COLOR_LEMONLIME_B 89
#define COLOR_LEMONLIME_HEX COLOR_LEMONLIME_R << 16 | COLOR_LEMONLIME_G  << 8 | COLOR_LEMONLIME_B


#define COLOR_LEMONYELLOW_R 253
#define COLOR_LEMONYELLOW_G 255
#define COLOR_LEMONYELLOW_B 0
#define COLOR_LEMONYELLOW_HEX COLOR_LEMONYELLOW_R << 16 | COLOR_LEMONYELLOW_G  << 8 | COLOR_LEMONYELLOW_B


#define COLOR_LICORICE_R 26
#define COLOR_LICORICE_G 17
#define COLOR_LICORICE_B 16
#define COLOR_LICORICE_HEX COLOR_LICORICE_R << 16 | COLOR_LICORICE_G  << 8 | COLOR_LICORICE_B


#define COLOR_LIGHTBLUE_R 173
#define COLOR_LIGHTBLUE_G 216
#define COLOR_LIGHTBLUE_B 230
#define COLOR_LIGHTBLUE_HEX COLOR_LIGHTBLUE_R << 16 | COLOR_LIGHTBLUE_G  << 8 | COLOR_LIGHTBLUE_B


#define COLOR_LIGHTBROWN_R 181
#define COLOR_LIGHTBROWN_G 101
#define COLOR_LIGHTBROWN_B 29
#define COLOR_LIGHTBROWN_HEX COLOR_LIGHTBROWN_R << 16 | COLOR_LIGHTBROWN_G  << 8 | COLOR_LIGHTBROWN_B


#define COLOR_LIGHTCORAL_R 240
#define COLOR_LIGHTCORAL_G 128
#define COLOR_LIGHTCORAL_B 128
#define COLOR_LIGHTCORAL_HEX COLOR_LIGHTCORAL_R << 16 | COLOR_LIGHTCORAL_G  << 8 | COLOR_LIGHTCORAL_B


#define COLOR_LIGHTCYAN_R 224
#define COLOR_LIGHTCYAN_G 255
#define COLOR_LIGHTCYAN_B 255
#define COLOR_LIGHTCYAN_HEX COLOR_LIGHTCYAN_R << 16 | COLOR_LIGHTCYAN_G  << 8 | COLOR_LIGHTCYAN_B


#define COLOR_LIGHTGOLDENRODYELLOW_R 250
#define COLOR_LIGHTGOLDENRODYELLOW_G 250
#define COLOR_LIGHTGOLDENRODYELLOW_B 210
#define COLOR_LIGHTGOLDENRODYELLOW_HEX COLOR_LIGHTGOLDENRODYELLOW_R << 16 | COLOR_LIGHTGOLDENRODYELLOW_G  << 8 | COLOR_LIGHTGOLDENRODYELLOW_B


#define COLOR_LIGHTGRAY_R 211
#define COLOR_LIGHTGRAY_G 211
#define COLOR_LIGHTGRAY_B 211
#define COLOR_LIGHTGRAY_HEX COLOR_LIGHTGRAY_R << 16 | COLOR_LIGHTGRAY_G  << 8 | COLOR_LIGHTGRAY_B


#define COLOR_LIGHTGREEN_R 144
#define COLOR_LIGHTGREEN_G 238
#define COLOR_LIGHTGREEN_B 144
#define COLOR_LIGHTGREEN_HEX COLOR_LIGHTGREEN_R << 16 | COLOR_LIGHTGREEN_G  << 8 | COLOR_LIGHTGREEN_B


#define COLOR_LIGHTOLIVEGREEN_R 152
#define COLOR_LIGHTOLIVEGREEN_G 191
#define COLOR_LIGHTOLIVEGREEN_B 100
#define COLOR_LIGHTOLIVEGREEN_HEX COLOR_LIGHTOLIVEGREEN_R << 16 | COLOR_LIGHTOLIVEGREEN_G  << 8 | COLOR_LIGHTOLIVEGREEN_B


#define COLOR_LIGHTPINK_R 255
#define COLOR_LIGHTPINK_G 182
#define COLOR_LIGHTPINK_B 193
#define COLOR_LIGHTPINK_HEX COLOR_LIGHTPINK_R << 16 | COLOR_LIGHTPINK_G  << 8 | COLOR_LIGHTPINK_B


#define COLOR_LIGHTSALMON_R 253
#define COLOR_LIGHTSALMON_G 171
#define COLOR_LIGHTSALMON_B 159
#define COLOR_LIGHTSALMON_HEX COLOR_LIGHTSALMON_R << 16 | COLOR_LIGHTSALMON_G  << 8 | COLOR_LIGHTSALMON_B


#define COLOR_LIGHTSEAGREEN_R 32
#define COLOR_LIGHTSEAGREEN_G 178
#define COLOR_LIGHTSEAGREEN_B 170
#define COLOR_LIGHTSEAGREEN_HEX COLOR_LIGHTSEAGREEN_R << 16 | COLOR_LIGHTSEAGREEN_G  << 8 | COLOR_LIGHTSEAGREEN_B


#define COLOR_LIGHTSKYBLUE_R 135
#define COLOR_LIGHTSKYBLUE_G 206
#define COLOR_LIGHTSKYBLUE_B 250
#define COLOR_LIGHTSKYBLUE_HEX COLOR_LIGHTSKYBLUE_R << 16 | COLOR_LIGHTSKYBLUE_G  << 8 | COLOR_LIGHTSKYBLUE_B


#define COLOR_LIGHTSLATEGRAY_R 119
#define COLOR_LIGHTSLATEGRAY_G 136
#define COLOR_LIGHTSLATEGRAY_B 153
#define COLOR_LIGHTSLATEGRAY_HEX COLOR_LIGHTSLATEGRAY_R << 16 | COLOR_LIGHTSLATEGRAY_G  << 8 | COLOR_LIGHTSLATEGRAY_B


#define COLOR_LIGHTSTEELBLUE_R 176
#define COLOR_LIGHTSTEELBLUE_G 196
#define COLOR_LIGHTSTEELBLUE_B 222
#define COLOR_LIGHTSTEELBLUE_HEX COLOR_LIGHTSTEELBLUE_R << 16 | COLOR_LIGHTSTEELBLUE_G  << 8 | COLOR_LIGHTSTEELBLUE_B


#define COLOR_LIGHTTAN_R 230
#define COLOR_LIGHTTAN_G 219
#define COLOR_LIGHTTAN_B 172
#define COLOR_LIGHTTAN_HEX COLOR_LIGHTTAN_R << 16 | COLOR_LIGHTTAN_G  << 8 | COLOR_LIGHTTAN_B


#define COLOR_LIGHTTEAL_R 72
#define COLOR_LIGHTTEAL_G 170
#define COLOR_LIGHTTEAL_B 173
#define COLOR_LIGHTTEAL_HEX COLOR_LIGHTTEAL_R << 16 | COLOR_LIGHTTEAL_G  << 8 | COLOR_LIGHTTEAL_B


#define COLOR_LIGHTYELLOW_R 255
#define COLOR_LIGHTYELLOW_G 255
#define COLOR_LIGHTYELLOW_B 224
#define COLOR_LIGHTYELLOW_HEX COLOR_LIGHTYELLOW_R << 16 | COLOR_LIGHTYELLOW_G  << 8 | COLOR_LIGHTYELLOW_B


#define COLOR_LIME_R 50
#define COLOR_LIME_G 205
#define COLOR_LIME_B 50
#define COLOR_LIME_HEX COLOR_LIME_R << 16 | COLOR_LIME_G  << 8 | COLOR_LIME_B


#define COLOR_LINEN_R 233
#define COLOR_LINEN_G 220
#define COLOR_LINEN_B 201
#define COLOR_LINEN_HEX COLOR_LINEN_R << 16 | COLOR_LINEN_G  << 8 | COLOR_LINEN_B


#define COLOR_LINKWHITE_R 236
#define COLOR_LINKWHITE_G 243
#define COLOR_LINKWHITE_B 249
#define COLOR_LINKWHITE_HEX COLOR_LINKWHITE_R << 16 | COLOR_LINKWHITE_G  << 8 | COLOR_LINKWHITE_B


#define COLOR_LIPSTICK_R 155
#define COLOR_LIPSTICK_G 16
#define COLOR_LIPSTICK_B 3
#define COLOR_LIPSTICK_HEX COLOR_LIPSTICK_R << 16 | COLOR_LIPSTICK_G  << 8 | COLOR_LIPSTICK_B


#define COLOR_LITTLEBOYBLUE_R 108
#define COLOR_LITTLEBOYBLUE_G 160
#define COLOR_LITTLEBOYBLUE_B 220
#define COLOR_LITTLEBOYBLUE_HEX COLOR_LITTLEBOYBLUE_R << 16 | COLOR_LITTLEBOYBLUE_G  << 8 | COLOR_LITTLEBOYBLUE_B


#define COLOR_MACAROON_R 249
#define COLOR_MACAROON_G 224
#define COLOR_MACAROON_B 118
#define COLOR_MACAROON_HEX COLOR_MACAROON_R << 16 | COLOR_MACAROON_G  << 8 | COLOR_MACAROON_B


#define COLOR_MAGENTAPROCESS_R 225
#define COLOR_MAGENTAPROCESS_G 21
#define COLOR_MAGENTAPROCESS_B 132
#define COLOR_MAGENTAPROCESS_HEX COLOR_MAGENTAPROCESS_R << 16 | COLOR_MAGENTAPROCESS_G  << 8 | COLOR_MAGENTAPROCESS_B


#define COLOR_MAGNOLIA_R 248
#define COLOR_MAGNOLIA_G 244
#define COLOR_MAGNOLIA_B 255
#define COLOR_MAGNOLIA_HEX COLOR_MAGNOLIA_R << 16 | COLOR_MAGNOLIA_G  << 8 | COLOR_MAGNOLIA_B


#define COLOR_MAHOGANY_R 66
#define COLOR_MAHOGANY_G 12
#define COLOR_MAHOGANY_B 9
#define COLOR_MAHOGANY_HEX COLOR_MAHOGANY_R << 16 | COLOR_MAHOGANY_G  << 8 | COLOR_MAHOGANY_B


#define COLOR_MANTIS_R 116
#define COLOR_MANTIS_G 195
#define COLOR_MANTIS_B 101
#define COLOR_MANTIS_HEX COLOR_MANTIS_R << 16 | COLOR_MANTIS_G  << 8 | COLOR_MANTIS_B


#define COLOR_MARDIGRAS_R 136
#define COLOR_MARDIGRAS_G 0
#define COLOR_MARDIGRAS_B 133
#define COLOR_MARDIGRAS_HEX COLOR_MARDIGRAS_R << 16 | COLOR_MARDIGRAS_G  << 8 | COLOR_MARDIGRAS_B


#define COLOR_MARENGO_R 76
#define COLOR_MARENGO_G 88
#define COLOR_MARENGO_B 102
#define COLOR_MARENGO_HEX COLOR_MARENGO_R << 16 | COLOR_MARENGO_G  << 8 | COLOR_MARENGO_B


#define COLOR_MARMALADE_R 209
#define COLOR_MARMALADE_G 96
#define COLOR_MARMALADE_B 2
#define COLOR_MARMALADE_HEX COLOR_MARMALADE_R << 16 | COLOR_MARMALADE_G  << 8 | COLOR_MARMALADE_B


#define COLOR_MAROON_R 128
#define COLOR_MAROON_G 0
#define COLOR_MAROON_B 0
#define COLOR_MAROON_HEX COLOR_MAROON_R << 16 | COLOR_MAROON_G  << 8 | COLOR_MAROON_B


#define COLOR_MAUVE_R 122
#define COLOR_MAUVE_G 73
#define COLOR_MAUVE_B 136
#define COLOR_MAUVE_HEX COLOR_MAUVE_R << 16 | COLOR_MAUVE_G  << 8 | COLOR_MAUVE_B


#define COLOR_MAYABLUE_R 115
#define COLOR_MAYABLUE_G 194
#define COLOR_MAYABLUE_B 251
#define COLOR_MAYABLUE_HEX COLOR_MAYABLUE_R << 16 | COLOR_MAYABLUE_G  << 8 | COLOR_MAYABLUE_B


#define COLOR_MEDIUMAQUAMARINE_R 102
#define COLOR_MEDIUMAQUAMARINE_G 205
#define COLOR_MEDIUMAQUAMARINE_B 170
#define COLOR_MEDIUMAQUAMARINE_HEX COLOR_MEDIUMAQUAMARINE_R << 16 | COLOR_MEDIUMAQUAMARINE_G  << 8 | COLOR_MEDIUMAQUAMARINE_B


#define COLOR_MEDIUMBLUE_R 0
#define COLOR_MEDIUMBLUE_G 0
#define COLOR_MEDIUMBLUE_B 205
#define COLOR_MEDIUMBLUE_HEX COLOR_MEDIUMBLUE_R << 16 | COLOR_MEDIUMBLUE_G  << 8 | COLOR_MEDIUMBLUE_B


#define COLOR_MEDIUMGRAY_R 190
#define COLOR_MEDIUMGRAY_G 190
#define COLOR_MEDIUMGRAY_B 190
#define COLOR_MEDIUMGRAY_HEX COLOR_MEDIUMGRAY_R << 16 | COLOR_MEDIUMGRAY_G  << 8 | COLOR_MEDIUMGRAY_B


#define COLOR_MEDIUMORCHID_R 186
#define COLOR_MEDIUMORCHID_G 85
#define COLOR_MEDIUMORCHID_B 211
#define COLOR_MEDIUMORCHID_HEX COLOR_MEDIUMORCHID_R << 16 | COLOR_MEDIUMORCHID_G  << 8 | COLOR_MEDIUMORCHID_B


#define COLOR_MEDIUMPURPLE_R 147
#define COLOR_MEDIUMPURPLE_G 112
#define COLOR_MEDIUMPURPLE_B 219
#define COLOR_MEDIUMPURPLE_HEX COLOR_MEDIUMPURPLE_R << 16 | COLOR_MEDIUMPURPLE_G  << 8 | COLOR_MEDIUMPURPLE_B


#define COLOR_MEDIUMSEAGREEN_R 60
#define COLOR_MEDIUMSEAGREEN_G 179
#define COLOR_MEDIUMSEAGREEN_B 113
#define COLOR_MEDIUMSEAGREEN_HEX COLOR_MEDIUMSEAGREEN_R << 16 | COLOR_MEDIUMSEAGREEN_G  << 8 | COLOR_MEDIUMSEAGREEN_B


#define COLOR_MEDIUMSLATEBLUE_R 123
#define COLOR_MEDIUMSLATEBLUE_G 104
#define COLOR_MEDIUMSLATEBLUE_B 238
#define COLOR_MEDIUMSLATEBLUE_HEX COLOR_MEDIUMSLATEBLUE_R << 16 | COLOR_MEDIUMSLATEBLUE_G  << 8 | COLOR_MEDIUMSLATEBLUE_B


#define COLOR_MEDIUMSPRINGGREEN_R 0
#define COLOR_MEDIUMSPRINGGREEN_G 250
#define COLOR_MEDIUMSPRINGGREEN_B 154
#define COLOR_MEDIUMSPRINGGREEN_HEX COLOR_MEDIUMSPRINGGREEN_R << 16 | COLOR_MEDIUMSPRINGGREEN_G  << 8 | COLOR_MEDIUMSPRINGGREEN_B


#define COLOR_MEDIUMTURQUOISE_R 72
#define COLOR_MEDIUMTURQUOISE_G 209
#define COLOR_MEDIUMTURQUOISE_B 204
#define COLOR_MEDIUMTURQUOISE_HEX COLOR_MEDIUMTURQUOISE_R << 16 | COLOR_MEDIUMTURQUOISE_G  << 8 | COLOR_MEDIUMTURQUOISE_B


#define COLOR_MEDIUMVERMILION_R 207
#define COLOR_MEDIUMVERMILION_G 91
#define COLOR_MEDIUMVERMILION_B 46
#define COLOR_MEDIUMVERMILION_HEX COLOR_MEDIUMVERMILION_R << 16 | COLOR_MEDIUMVERMILION_G  << 8 | COLOR_MEDIUMVERMILION_B


#define COLOR_MEDIUMVIOLETRED_R 199
#define COLOR_MEDIUMVIOLETRED_G 21
#define COLOR_MEDIUMVIOLETRED_B 133
#define COLOR_MEDIUMVIOLETRED_HEX COLOR_MEDIUMVIOLETRED_R << 16 | COLOR_MEDIUMVIOLETRED_G  << 8 | COLOR_MEDIUMVIOLETRED_B


#define COLOR_MERIGOLD_R 252
#define COLOR_MERIGOLD_G 174
#define COLOR_MERIGOLD_B 30
#define COLOR_MERIGOLD_HEX COLOR_MERIGOLD_R << 16 | COLOR_MERIGOLD_G  << 8 | COLOR_MERIGOLD_B


#define COLOR_MERLOT_R 84
#define COLOR_MERLOT_G 30
#define COLOR_MERLOT_B 27
#define COLOR_MERLOT_HEX COLOR_MERLOT_R << 16 | COLOR_MERLOT_G  << 8 | COLOR_MERLOT_B


#define COLOR_METAL_R 14
#define COLOR_METAL_G 12
#define COLOR_METAL_B 10
#define COLOR_METAL_HEX COLOR_METAL_R << 16 | COLOR_METAL_G  << 8 | COLOR_METAL_B


#define COLOR_METALLICORANGE_R 226
#define COLOR_METALLICORANGE_G 99
#define COLOR_METALLICORANGE_B 16
#define COLOR_METALLICORANGE_HEX COLOR_METALLICORANGE_R << 16 | COLOR_METALLICORANGE_G  << 8 | COLOR_METALLICORANGE_B


#define COLOR_MIDNIGHT_R 4
#define COLOR_MIDNIGHT_G 4
#define COLOR_MIDNIGHT_B 6
#define COLOR_MIDNIGHT_HEX COLOR_MIDNIGHT_R << 16 | COLOR_MIDNIGHT_G  << 8 | COLOR_MIDNIGHT_B


#define COLOR_MIDNIGHTBLUE_R 25
#define COLOR_MIDNIGHTBLUE_G 25
#define COLOR_MIDNIGHTBLUE_B 112
#define COLOR_MIDNIGHTBLUE_HEX COLOR_MIDNIGHTBLUE_R << 16 | COLOR_MIDNIGHTBLUE_G  << 8 | COLOR_MIDNIGHTBLUE_B


#define COLOR_MILK_R 253
#define COLOR_MILK_G 255
#define COLOR_MILK_B 245
#define COLOR_MILK_HEX COLOR_MILK_R << 16 | COLOR_MILK_G  << 8 | COLOR_MILK_B


#define COLOR_MINT_R 153
#define COLOR_MINT_G 237
#define COLOR_MINT_B 195
#define COLOR_MINT_HEX COLOR_MINT_R << 16 | COLOR_MINT_G  << 8 | COLOR_MINT_B


#define COLOR_MINTCREAM_R 245
#define COLOR_MINTCREAM_G 255
#define COLOR_MINTCREAM_B 250
#define COLOR_MINTCREAM_HEX COLOR_MINTCREAM_R << 16 | COLOR_MINTCREAM_G  << 8 | COLOR_MINTCREAM_B


#define COLOR_MISTYROSE_R 255
#define COLOR_MISTYROSE_G 228
#define COLOR_MISTYROSE_B 225
#define COLOR_MISTYROSE_HEX COLOR_MISTYROSE_R << 16 | COLOR_MISTYROSE_G  << 8 | COLOR_MISTYROSE_B


#define COLOR_MOCCASIN_R 255
#define COLOR_MOCCASIN_G 228
#define COLOR_MOCCASIN_B 181
#define COLOR_MOCCASIN_HEX COLOR_MOCCASIN_R << 16 | COLOR_MOCCASIN_G  << 8 | COLOR_MOCCASIN_B


#define COLOR_MOCHA_R 60
#define COLOR_MOCHA_G 40
#define COLOR_MOCHA_B 13
#define COLOR_MOCHA_HEX COLOR_MOCHA_R << 16 | COLOR_MOCHA_G  << 8 | COLOR_MOCHA_B


#define COLOR_MOSS_R 70
#define COLOR_MOSS_G 109
#define COLOR_MOSS_B 29
#define COLOR_MOSS_HEX COLOR_MOSS_R << 16 | COLOR_MOSS_G  << 8 | COLOR_MOSS_B


#define COLOR_NAVAJOWHITE_R 255
#define COLOR_NAVAJOWHITE_G 222
#define COLOR_NAVAJOWHITE_B 173
#define COLOR_NAVAJOWHITE_HEX COLOR_NAVAJOWHITE_R << 16 | COLOR_NAVAJOWHITE_G  << 8 | COLOR_NAVAJOWHITE_B


#define COLOR_NAVY_R 0
#define COLOR_NAVY_G 0
#define COLOR_NAVY_B 128
#define COLOR_NAVY_HEX COLOR_NAVY_R << 16 | COLOR_NAVY_G  << 8 | COLOR_NAVY_B


#define COLOR_NEONPINK_R 255
#define COLOR_NEONPINK_G 110
#define COLOR_NEONPINK_B 199
#define COLOR_NEONPINK_HEX COLOR_NEONPINK_R << 16 | COLOR_NEONPINK_G  << 8 | COLOR_NEONPINK_B


#define COLOR_NEUTRALBLACK_R 11
#define COLOR_NEUTRALBLACK_G 11
#define COLOR_NEUTRALBLACK_B 11
#define COLOR_NEUTRALBLACK_HEX COLOR_NEUTRALBLACK_R << 16 | COLOR_NEUTRALBLACK_G  << 8 | COLOR_NEUTRALBLACK_B


#define COLOR_NEVADA_R 102
#define COLOR_NEVADA_G 106
#define COLOR_NEVADA_B 109
#define COLOR_NEVADA_HEX COLOR_NEVADA_R << 16 | COLOR_NEVADA_G  << 8 | COLOR_NEVADA_B


#define COLOR_NICKEL_R 114
#define COLOR_NICKEL_G 116
#define COLOR_NICKEL_B 114
#define COLOR_NICKEL_HEX COLOR_NICKEL_R << 16 | COLOR_NICKEL_G  << 8 | COLOR_NICKEL_B


#define COLOR_NIGHT_R 12
#define COLOR_NIGHT_G 9
#define COLOR_NIGHT_B 10
#define COLOR_NIGHT_HEX COLOR_NIGHT_R << 16 | COLOR_NIGHT_G  << 8 | COLOR_NIGHT_B


#define COLOR_NIGHTGREY_R 120
#define COLOR_NIGHTGREY_G 120
#define COLOR_NIGHTGREY_B 120
#define COLOR_NIGHTGREY_HEX COLOR_NIGHTGREY_R << 16 | COLOR_NIGHTGREY_G  << 8 | COLOR_NIGHTGREY_B


#define COLOR_NORTHWESTERNPURPLE_R 78
#define COLOR_NORTHWESTERNPURPLE_G 42
#define COLOR_NORTHWESTERNPURPLE_B 132
#define COLOR_NORTHWESTERNPURPLE_HEX COLOR_NORTHWESTERNPURPLE_R << 16 | COLOR_NORTHWESTERNPURPLE_G  << 8 | COLOR_NORTHWESTERNPURPLE_B


#define COLOR_OAT_R 223
#define COLOR_OAT_G 201
#define COLOR_OAT_B 138
#define COLOR_OAT_HEX COLOR_OAT_R << 16 | COLOR_OAT_G  << 8 | COLOR_OAT_B


#define COLOR_OBSIDIAN_R 2
#define COLOR_OBSIDIAN_G 4
#define COLOR_OBSIDIAN_B 3
#define COLOR_OBSIDIAN_HEX COLOR_OBSIDIAN_R << 16 | COLOR_OBSIDIAN_G  << 8 | COLOR_OBSIDIAN_B


#define COLOR_OCEAN_R 1
#define COLOR_OCEAN_G 96
#define COLOR_OCEAN_B 100
#define COLOR_OCEAN_HEX COLOR_OCEAN_R << 16 | COLOR_OCEAN_G  << 8 | COLOR_OCEAN_B


#define COLOR_OCHRE_R 204
#define COLOR_OCHRE_G 119
#define COLOR_OCHRE_B 34
#define COLOR_OCHRE_HEX COLOR_OCHRE_R << 16 | COLOR_OCHRE_G  << 8 | COLOR_OCHRE_B


#define COLOR_OIL_R 5
#define COLOR_OIL_G 1
#define COLOR_OIL_B 0
#define COLOR_OIL_HEX COLOR_OIL_R << 16 | COLOR_OIL_G  << 8 | COLOR_OIL_B


#define COLOR_OLDLACE_R 253
#define COLOR_OLDLACE_G 245
#define COLOR_OLDLACE_B 230
#define COLOR_OLDLACE_HEX COLOR_OLDLACE_R << 16 | COLOR_OLDLACE_G  << 8 | COLOR_OLDLACE_B


#define COLOR_OLIVE_R 128
#define COLOR_OLIVE_G 128
#define COLOR_OLIVE_B 0
#define COLOR_OLIVE_HEX COLOR_OLIVE_R << 16 | COLOR_OLIVE_G  << 8 | COLOR_OLIVE_B


#define COLOR_OLIVEDRAB_R 107
#define COLOR_OLIVEDRAB_G 142
#define COLOR_OLIVEDRAB_B 35
#define COLOR_OLIVEDRAB_HEX COLOR_OLIVEDRAB_R << 16 | COLOR_OLIVEDRAB_G  << 8 | COLOR_OLIVEDRAB_B


#define COLOR_OLIVEGREEN_R 85
#define COLOR_OLIVEGREEN_G 107
#define COLOR_OLIVEGREEN_B 47
#define COLOR_OLIVEGREEN_HEX COLOR_OLIVEGREEN_R << 16 | COLOR_OLIVEGREEN_G  << 8 | COLOR_OLIVEGREEN_B


#define COLOR_ONYX_R 3
#define COLOR_ONYX_G 1
#define COLOR_ONYX_B 4
#define COLOR_ONYX_HEX COLOR_ONYX_R << 16 | COLOR_ONYX_G  << 8 | COLOR_ONYX_B


#define COLOR_ORANGE_R 255
#define COLOR_ORANGE_G 165
#define COLOR_ORANGE_B 0
#define COLOR_ORANGE_HEX COLOR_ORANGE_R << 16 | COLOR_ORANGE_G  << 8 | COLOR_ORANGE_B


#define COLOR_ORANGERED_R 255
#define COLOR_ORANGERED_G 69
#define COLOR_ORANGERED_B 0
#define COLOR_ORANGERED_HEX COLOR_ORANGERED_R << 16 | COLOR_ORANGERED_G  << 8 | COLOR_ORANGERED_B


#define COLOR_ORCHID_R 218
#define COLOR_ORCHID_G 112
#define COLOR_ORCHID_B 214
#define COLOR_ORCHID_HEX COLOR_ORCHID_R << 16 | COLOR_ORCHID_G  << 8 | COLOR_ORCHID_B


#define COLOR_OUTERSPACE_R 65
#define COLOR_OUTERSPACE_G 74
#define COLOR_OUTERSPACE_B 76
#define COLOR_OUTERSPACE_HEX COLOR_OUTERSPACE_R << 16 | COLOR_OUTERSPACE_G  << 8 | COLOR_OUTERSPACE_B


#define COLOR_OYSTER_R 220
#define COLOR_OYSTER_G 215
#define COLOR_OYSTER_B 160
#define COLOR_OYSTER_HEX COLOR_OYSTER_R << 16 | COLOR_OYSTER_G  << 8 | COLOR_OYSTER_B


#define COLOR_PAKISTANGREEN_R 0
#define COLOR_PAKISTANGREEN_G 102
#define COLOR_PAKISTANGREEN_B 0
#define COLOR_PAKISTANGREEN_HEX COLOR_PAKISTANGREEN_R << 16 | COLOR_PAKISTANGREEN_G  << 8 | COLOR_PAKISTANGREEN_B


#define COLOR_PALATINATE_R 114
#define COLOR_PALATINATE_G 36
#define COLOR_PALATINATE_B 108
#define COLOR_PALATINATE_HEX COLOR_PALATINATE_R << 16 | COLOR_PALATINATE_G  << 8 | COLOR_PALATINATE_B


#define COLOR_PALEGOLDENROD_R 238
#define COLOR_PALEGOLDENROD_G 232
#define COLOR_PALEGOLDENROD_B 170
#define COLOR_PALEGOLDENROD_HEX COLOR_PALEGOLDENROD_R << 16 | COLOR_PALEGOLDENROD_G  << 8 | COLOR_PALEGOLDENROD_B


#define COLOR_PALEGREEN_R 152
#define COLOR_PALEGREEN_G 251
#define COLOR_PALEGREEN_B 152
#define COLOR_PALEGREEN_HEX COLOR_PALEGREEN_R << 16 | COLOR_PALEGREEN_G  << 8 | COLOR_PALEGREEN_B


#define COLOR_PALEIVORY_R 253
#define COLOR_PALEIVORY_G 246
#define COLOR_PALEIVORY_B 228
#define COLOR_PALEIVORY_HEX COLOR_PALEIVORY_R << 16 | COLOR_PALEIVORY_G  << 8 | COLOR_PALEIVORY_B


#define COLOR_PALETURQUOISE_R 175
#define COLOR_PALETURQUOISE_G 238
#define COLOR_PALETURQUOISE_B 238
#define COLOR_PALETURQUOISE_HEX COLOR_PALETURQUOISE_R << 16 | COLOR_PALETURQUOISE_G  << 8 | COLOR_PALETURQUOISE_B


#define COLOR_PALEVIOLETRED_R 219
#define COLOR_PALEVIOLETRED_G 112
#define COLOR_PALEVIOLETRED_B 147
#define COLOR_PALEVIOLETRED_HEX COLOR_PALEVIOLETRED_R << 16 | COLOR_PALEVIOLETRED_G  << 8 | COLOR_PALEVIOLETRED_B


#define COLOR_PANSYPURPLE_R 120
#define COLOR_PANSYPURPLE_G 24
#define COLOR_PANSYPURPLE_B 74
#define COLOR_PANSYPURPLE_HEX COLOR_PANSYPURPLE_R << 16 | COLOR_PANSYPURPLE_G  << 8 | COLOR_PANSYPURPLE_B


#define COLOR_PAPAYAWHIP_R 255
#define COLOR_PAPAYAWHIP_G 239
#define COLOR_PAPAYAWHIP_B 213
#define COLOR_PAPAYAWHIP_HEX COLOR_PAPAYAWHIP_R << 16 | COLOR_PAPAYAWHIP_G  << 8 | COLOR_PAPAYAWHIP_B


#define COLOR_PARAKEET_R 3
#define COLOR_PARAKEET_G 192
#define COLOR_PARAKEET_B 74
#define COLOR_PARAKEET_HEX COLOR_PARAKEET_R << 16 | COLOR_PARAKEET_G  << 8 | COLOR_PARAKEET_B


#define COLOR_PARCHMENT_R 251
#define COLOR_PARCHMENT_G 245
#define COLOR_PARCHMENT_B 223
#define COLOR_PARCHMENT_HEX COLOR_PARCHMENT_R << 16 | COLOR_PARCHMENT_G  << 8 | COLOR_PARCHMENT_B


#define COLOR_PARISGREEN_R 80
#define COLOR_PARISGREEN_G 200
#define COLOR_PARISGREEN_B 120
#define COLOR_PARISGREEN_HEX COLOR_PARISGREEN_R << 16 | COLOR_PARISGREEN_G  << 8 | COLOR_PARISGREEN_B


#define COLOR_PARMESAN_R 253
#define COLOR_PARMESAN_G 233
#define COLOR_PARMESAN_B 146
#define COLOR_PARMESAN_HEX COLOR_PARMESAN_R << 16 | COLOR_PARMESAN_G  << 8 | COLOR_PARMESAN_B


#define COLOR_PASTELORANGE_R 254
#define COLOR_PASTELORANGE_G 186
#define COLOR_PASTELORANGE_B 79
#define COLOR_PASTELORANGE_HEX COLOR_PASTELORANGE_R << 16 | COLOR_PASTELORANGE_G  << 8 | COLOR_PASTELORANGE_B


#define COLOR_PASTELPINK_R 255
#define COLOR_PASTELPINK_G 209
#define COLOR_PASTELPINK_B 220
#define COLOR_PASTELPINK_HEX COLOR_PASTELPINK_R << 16 | COLOR_PASTELPINK_G  << 8 | COLOR_PASTELPINK_B


#define COLOR_PEACH_R 252
#define COLOR_PEACH_G 148
#define COLOR_PEACH_B 131
#define COLOR_PEACH_HEX COLOR_PEACH_R << 16 | COLOR_PEACH_G  << 8 | COLOR_PEACH_B


#define COLOR_PEACHPUFF_R 255
#define COLOR_PEACHPUFF_G 218
#define COLOR_PEACHPUFF_B 185
#define COLOR_PEACHPUFF_HEX COLOR_PEACHPUFF_R << 16 | COLOR_PEACHPUFF_G  << 8 | COLOR_PEACHPUFF_B


#define COLOR_PEACOCK_R 2
#define COLOR_PEACOCK_G 45
#define COLOR_PEACOCK_B 54
#define COLOR_PEACOCK_HEX COLOR_PEACOCK_R << 16 | COLOR_PEACOCK_G  << 8 | COLOR_PEACOCK_B


#define COLOR_PEANUTBROWN_R 121
#define COLOR_PEANUTBROWN_G 92
#define COLOR_PEANUTBROWN_B 52
#define COLOR_PEANUTBROWN_HEX COLOR_PEANUTBROWN_R << 16 | COLOR_PEANUTBROWN_G  << 8 | COLOR_PEANUTBROWN_B


#define COLOR_PEAR_R 116
#define COLOR_PEAR_G 183
#define COLOR_PEAR_B 46
#define COLOR_PEAR_HEX COLOR_PEAR_R << 16 | COLOR_PEAR_G  << 8 | COLOR_PEAR_B


#define COLOR_PEARL_R 251
#define COLOR_PEARL_G 252
#define COLOR_PEARL_B 248
#define COLOR_PEARL_HEX COLOR_PEARL_R << 16 | COLOR_PEARL_G  << 8 | COLOR_PEARL_B


#define COLOR_PEBBLE_R 51
#define COLOR_PEBBLE_G 51
#define COLOR_PEBBLE_B 51
#define COLOR_PEBBLE_HEX COLOR_PEBBLE_R << 16 | COLOR_PEBBLE_G  << 8 | COLOR_PEBBLE_B


#define COLOR_PECAN_R 74
#define COLOR_PECAN_G 37
#define COLOR_PECAN_B 17
#define COLOR_PECAN_HEX COLOR_PECAN_R << 16 | COLOR_PECAN_G  << 8 | COLOR_PECAN_B


#define COLOR_PENNY_R 83
#define COLOR_PENNY_G 41
#define COLOR_PENNY_B 21
#define COLOR_PENNY_HEX COLOR_PENNY_R << 16 | COLOR_PENNY_G  << 8 | COLOR_PENNY_B


#define COLOR_PEPPERMINT_R 241
#define COLOR_PEPPERMINT_G 249
#define COLOR_PEPPERMINT_B 236
#define COLOR_PEPPERMINT_HEX COLOR_PEPPERMINT_R << 16 | COLOR_PEPPERMINT_G  << 8 | COLOR_PEPPERMINT_B


#define COLOR_PERSIANGREEN_R 0
#define COLOR_PERSIANGREEN_G 166
#define COLOR_PERSIANGREEN_B 147
#define COLOR_PERSIANGREEN_HEX COLOR_PERSIANGREEN_R << 16 | COLOR_PERSIANGREEN_G  << 8 | COLOR_PERSIANGREEN_B


#define COLOR_PERSIANPINK_R 247
#define COLOR_PERSIANPINK_G 127
#define COLOR_PERSIANPINK_B 190
#define COLOR_PERSIANPINK_HEX COLOR_PERSIANPINK_R << 16 | COLOR_PERSIANPINK_G  << 8 | COLOR_PERSIANPINK_B


#define COLOR_PERSIANRED_R 202
#define COLOR_PERSIANRED_G 52
#define COLOR_PERSIANRED_B 51
#define COLOR_PERSIANRED_HEX COLOR_PERSIANRED_R << 16 | COLOR_PERSIANRED_G  << 8 | COLOR_PERSIANRED_B


#define COLOR_PERU_R 205
#define COLOR_PERU_G 133
#define COLOR_PERU_B 63
#define COLOR_PERU_HEX COLOR_PERU_R << 16 | COLOR_PERU_G  << 8 | COLOR_PERU_B


#define COLOR_PEWTER_R 105
#define COLOR_PEWTER_G 104
#define COLOR_PEWTER_B 128
#define COLOR_PEWTER_HEX COLOR_PEWTER_R << 16 | COLOR_PEWTER_G  << 8 | COLOR_PEWTER_B


#define COLOR_PHILIPPINEORANGE_R 242
#define COLOR_PHILIPPINEORANGE_G 110
#define COLOR_PHILIPPINEORANGE_B 1
#define COLOR_PHILIPPINEORANGE_HEX COLOR_PHILIPPINEORANGE_R << 16 | COLOR_PHILIPPINEORANGE_G  << 8 | COLOR_PHILIPPINEORANGE_B


#define COLOR_PICKLE_R 89
#define COLOR_PICKLE_G 125
#define COLOR_PICKLE_B 53
#define COLOR_PICKLE_HEX COLOR_PICKLE_R << 16 | COLOR_PICKLE_G  << 8 | COLOR_PICKLE_B


#define COLOR_PIGGYPINK_R 253
#define COLOR_PIGGYPINK_G 221
#define COLOR_PIGGYPINK_B 230
#define COLOR_PIGGYPINK_HEX COLOR_PIGGYPINK_R << 16 | COLOR_PIGGYPINK_G  << 8 | COLOR_PIGGYPINK_B


#define COLOR_PINE_R 35
#define COLOR_PINE_G 79
#define COLOR_PINE_B 30
#define COLOR_PINE_HEX COLOR_PINE_R << 16 | COLOR_PINE_G  << 8 | COLOR_PINE_B


#define COLOR_PINK_R 255
#define COLOR_PINK_G 192
#define COLOR_PINK_B 203
#define COLOR_PINK_HEX COLOR_PINK_R << 16 | COLOR_PINK_G  << 8 | COLOR_PINK_B


#define COLOR_PINKISHPURPLE_R 163
#define COLOR_PINKISHPURPLE_G 44
#define COLOR_PINKISHPURPLE_B 196
#define COLOR_PINKISHPURPLE_HEX COLOR_PINKISHPURPLE_R << 16 | COLOR_PINKISHPURPLE_G  << 8 | COLOR_PINKISHPURPLE_B


#define COLOR_PINKSALT_R 248
#define COLOR_PINKSALT_G 238
#define COLOR_PINKSALT_B 236
#define COLOR_PINKSALT_HEX COLOR_PINKSALT_R << 16 | COLOR_PINKSALT_G  << 8 | COLOR_PINKSALT_B


#define COLOR_PISTACHIO_R 147
#define COLOR_PISTACHIO_G 197
#define COLOR_PISTACHIO_B 114
#define COLOR_PISTACHIO_HEX COLOR_PISTACHIO_R << 16 | COLOR_PISTACHIO_G  << 8 | COLOR_PISTACHIO_B


#define COLOR_PITCH_R 3
#define COLOR_PITCH_G 0
#define COLOR_PITCH_B 1
#define COLOR_PITCH_HEX COLOR_PITCH_R << 16 | COLOR_PITCH_G  << 8 | COLOR_PITCH_B


#define COLOR_PLUM_R 103
#define COLOR_PLUM_G 49
#define COLOR_PLUM_B 71
#define COLOR_PLUM_HEX COLOR_PLUM_R << 16 | COLOR_PLUM_G  << 8 | COLOR_PLUM_B


#define COLOR_PLUMPINK_R 221
#define COLOR_PLUMPINK_G 160
#define COLOR_PLUMPINK_B 221
#define COLOR_PLUMPINK_HEX COLOR_PLUMPINK_R << 16 | COLOR_PLUMPINK_G  << 8 | COLOR_PLUMPINK_B


#define COLOR_POMPANDPOWER_R 134
#define COLOR_POMPANDPOWER_G 96
#define COLOR_POMPANDPOWER_B 142
#define COLOR_POMPANDPOWER_HEX COLOR_POMPANDPOWER_R << 16 | COLOR_POMPANDPOWER_G  << 8 | COLOR_POMPANDPOWER_B


#define COLOR_PORCELAIN_R 255
#define COLOR_PORCELAIN_G 254
#define COLOR_PORCELAIN_B 252
#define COLOR_PORCELAIN_HEX COLOR_PORCELAIN_R << 16 | COLOR_PORCELAIN_G  << 8 | COLOR_PORCELAIN_B


#define COLOR_PORPOISE_R 77
#define COLOR_PORPOISE_G 76
#define COLOR_PORPOISE_B 92
#define COLOR_PORPOISE_HEX COLOR_PORPOISE_R << 16 | COLOR_PORPOISE_G  << 8 | COLOR_PORPOISE_B


#define COLOR_POWDER_R 251
#define COLOR_POWDER_G 252
#define COLOR_POWDER_B 250
#define COLOR_POWDER_HEX COLOR_POWDER_R << 16 | COLOR_POWDER_G  << 8 | COLOR_POWDER_B


#define COLOR_POWDERBLUE_R 176
#define COLOR_POWDERBLUE_G 224
#define COLOR_POWDERBLUE_B 230
#define COLOR_POWDERBLUE_HEX COLOR_POWDERBLUE_R << 16 | COLOR_POWDERBLUE_G  << 8 | COLOR_POWDERBLUE_B


#define COLOR_POWERBLACK_R 14
#define COLOR_POWERBLACK_G 12
#define COLOR_POWERBLACK_B 1
#define COLOR_POWERBLACK_HEX COLOR_POWERBLACK_R << 16 | COLOR_POWERBLACK_G  << 8 | COLOR_POWERBLACK_B


#define COLOR_PREMIUMBLACK_R 16
#define COLOR_PREMIUMBLACK_G 0
#define COLOR_PREMIUMBLACK_B 0
#define COLOR_PREMIUMBLACK_HEX COLOR_PREMIUMBLACK_R << 16 | COLOR_PREMIUMBLACK_G  << 8 | COLOR_PREMIUMBLACK_B


#define COLOR_PRINCETONORANGE_R 255
#define COLOR_PRINCETONORANGE_G 143
#define COLOR_PRINCETONORANGE_B 0
#define COLOR_PRINCETONORANGE_HEX COLOR_PRINCETONORANGE_R << 16 | COLOR_PRINCETONORANGE_G  << 8 | COLOR_PRINCETONORANGE_B


#define COLOR_PRISMATICRED_R 208
#define COLOR_PRISMATICRED_G 61
#define COLOR_PRISMATICRED_B 51
#define COLOR_PRISMATICRED_HEX COLOR_PRISMATICRED_R << 16 | COLOR_PRISMATICRED_G  << 8 | COLOR_PRISMATICRED_B


#define COLOR_PUMPKIN_R 245
#define COLOR_PUMPKIN_G 118
#define COLOR_PUMPKIN_B 26
#define COLOR_PUMPKIN_HEX COLOR_PUMPKIN_R << 16 | COLOR_PUMPKIN_G  << 8 | COLOR_PUMPKIN_B


#define COLOR_PUNCH_R 242
#define COLOR_PUNCH_G 82
#define COLOR_PUNCH_B 120
#define COLOR_PUNCH_HEX COLOR_PUNCH_R << 16 | COLOR_PUNCH_G  << 8 | COLOR_PUNCH_B


#define COLOR_PURPLE_R 128
#define COLOR_PURPLE_G 0
#define COLOR_PURPLE_B 128
#define COLOR_PURPLE_HEX COLOR_PURPLE_R << 16 | COLOR_PURPLE_G  << 8 | COLOR_PURPLE_B


#define COLOR_PURPUREUS_R 154
#define COLOR_PURPUREUS_G 78
#define COLOR_PURPUREUS_B 174
#define COLOR_PURPUREUS_HEX COLOR_PURPUREUS_R << 16 | COLOR_PURPUREUS_G  << 8 | COLOR_PURPUREUS_B


#define COLOR_RAISIN_R 41
#define COLOR_RAISIN_G 9
#define COLOR_RAISIN_B 22
#define COLOR_RAISIN_HEX COLOR_RAISIN_R << 16 | COLOR_RAISIN_G  << 8 | COLOR_RAISIN_B


#define COLOR_RAISINBLACK_R 36
#define COLOR_RAISINBLACK_G 33
#define COLOR_RAISINBLACK_B 36
#define COLOR_RAISINBLACK_HEX COLOR_RAISINBLACK_R << 16 | COLOR_RAISINBLACK_G  << 8 | COLOR_RAISINBLACK_B


#define COLOR_RASPBERRY_R 210
#define COLOR_RASPBERRY_G 31
#define COLOR_RASPBERRY_B 60
#define COLOR_RASPBERRY_HEX COLOR_RASPBERRY_R << 16 | COLOR_RASPBERRY_G  << 8 | COLOR_RASPBERRY_B


#define COLOR_RAVEN_R 5
#define COLOR_RAVEN_G 3
#define COLOR_RAVEN_B 1
#define COLOR_RAVEN_HEX COLOR_RAVEN_R << 16 | COLOR_RAVEN_G  << 8 | COLOR_RAVEN_B


#define COLOR_RAZZMATAZZ_R 227
#define COLOR_RAZZMATAZZ_G 37
#define COLOR_RAZZMATAZZ_B 107
#define COLOR_RAZZMATAZZ_HEX COLOR_RAZZMATAZZ_R << 16 | COLOR_RAZZMATAZZ_G  << 8 | COLOR_RAZZMATAZZ_B


#define COLOR_REALORANGE_R 237
#define COLOR_REALORANGE_G 112
#define COLOR_REALORANGE_B 20
#define COLOR_REALORANGE_HEX COLOR_REALORANGE_R << 16 | COLOR_REALORANGE_G  << 8 | COLOR_REALORANGE_B


#define COLOR_REBECCAPURPLE_R 102
#define COLOR_REBECCAPURPLE_G 51
#define COLOR_REBECCAPURPLE_B 153
#define COLOR_REBECCAPURPLE_HEX COLOR_REBECCAPURPLE_R << 16 | COLOR_REBECCAPURPLE_G  << 8 | COLOR_REBECCAPURPLE_B


#define COLOR_RED_R 255
#define COLOR_RED_G 0
#define COLOR_RED_B 0
#define COLOR_RED_HEX COLOR_RED_R << 16 | COLOR_RED_G  << 8 | COLOR_RED_B


#define COLOR_RICE_R 250
#define COLOR_RICE_G 245
#define COLOR_RICE_B 239
#define COLOR_RICE_HEX COLOR_RICE_R << 16 | COLOR_RICE_G  << 8 | COLOR_RICE_B


#define COLOR_ROASTEDCOFFEE_R 75
#define COLOR_ROASTEDCOFFEE_G 55
#define COLOR_ROASTEDCOFFEE_B 28
#define COLOR_ROASTEDCOFFEE_HEX COLOR_ROASTEDCOFFEE_R << 16 | COLOR_ROASTEDCOFFEE_G  << 8 | COLOR_ROASTEDCOFFEE_B


#define COLOR_ROCKETMETALLIC_R 138
#define COLOR_ROCKETMETALLIC_G 127
#define COLOR_ROCKETMETALLIC_B 141
#define COLOR_ROCKETMETALLIC_HEX COLOR_ROCKETMETALLIC_R << 16 | COLOR_ROCKETMETALLIC_G  << 8 | COLOR_ROCKETMETALLIC_B


#define COLOR_ROSE_R 243
#define COLOR_ROSE_G 58
#define COLOR_ROSE_B 106
#define COLOR_ROSE_HEX COLOR_ROSE_R << 16 | COLOR_ROSE_G  << 8 | COLOR_ROSE_B


#define COLOR_ROSEPINK_R 252
#define COLOR_ROSEPINK_G 148
#define COLOR_ROSEPINK_B 175
#define COLOR_ROSEPINK_HEX COLOR_ROSEPINK_R << 16 | COLOR_ROSEPINK_G  << 8 | COLOR_ROSEPINK_B


#define COLOR_ROSEWHITE_R 255
#define COLOR_ROSEWHITE_G 250
#define COLOR_ROSEWHITE_B 250
#define COLOR_ROSEWHITE_HEX COLOR_ROSEWHITE_R << 16 | COLOR_ROSEWHITE_G  << 8 | COLOR_ROSEWHITE_B


#define COLOR_ROSEWOOD_R 158
#define COLOR_ROSEWOOD_G 66
#define COLOR_ROSEWOOD_B 68
#define COLOR_ROSEWOOD_HEX COLOR_ROSEWOOD_R << 16 | COLOR_ROSEWOOD_G  << 8 | COLOR_ROSEWOOD_B


#define COLOR_ROSYBROWN_R 188
#define COLOR_ROSYBROWN_G 143
#define COLOR_ROSYBROWN_B 143
#define COLOR_ROSYBROWN_HEX COLOR_ROSYBROWN_R << 16 | COLOR_ROSYBROWN_G  << 8 | COLOR_ROSYBROWN_B


#define COLOR_ROUGE_R 242
#define COLOR_ROUGE_G 107
#define COLOR_ROUGE_B 138
#define COLOR_ROUGE_HEX COLOR_ROUGE_R << 16 | COLOR_ROUGE_G  << 8 | COLOR_ROUGE_B


#define COLOR_ROYALBLUE_R 4
#define COLOR_ROYALBLUE_G 22
#define COLOR_ROYALBLUE_B 144
#define COLOR_ROYALBLUE_HEX COLOR_ROYALBLUE_R << 16 | COLOR_ROYALBLUE_G  << 8 | COLOR_ROYALBLUE_B


#define COLOR_ROYALORANGE_R 255
#define COLOR_ROYALORANGE_G 153
#define COLOR_ROYALORANGE_B 68
#define COLOR_ROYALORANGE_HEX COLOR_ROYALORANGE_R << 16 | COLOR_ROYALORANGE_G  << 8 | COLOR_ROYALORANGE_B


#define COLOR_ROYALPERIWINKLE_R 190
#define COLOR_ROYALPERIWINKLE_G 147
#define COLOR_ROYALPERIWINKLE_B 212
#define COLOR_ROYALPERIWINKLE_HEX COLOR_ROYALPERIWINKLE_R << 16 | COLOR_ROYALPERIWINKLE_G  << 8 | COLOR_ROYALPERIWINKLE_B


#define COLOR_ROYALYELLOW_R 250
#define COLOR_ROYALYELLOW_G 218
#define COLOR_ROYALYELLOW_B 94
#define COLOR_ROYALYELLOW_HEX COLOR_ROYALYELLOW_R << 16 | COLOR_ROYALYELLOW_G  << 8 | COLOR_ROYALYELLOW_B


#define COLOR_RUBY_R 238
#define COLOR_RUBY_G 40
#define COLOR_RUBY_B 40
#define COLOR_RUBY_HEX COLOR_RUBY_R << 16 | COLOR_RUBY_G  << 8 | COLOR_RUBY_B


#define COLOR_RUDDYBLUE_R 118
#define COLOR_RUDDYBLUE_G 171
#define COLOR_RUDDYBLUE_B 223
#define COLOR_RUDDYBLUE_HEX COLOR_RUDDYBLUE_R << 16 | COLOR_RUDDYBLUE_G  << 8 | COLOR_RUDDYBLUE_B


#define COLOR_RUSSET_R 128
#define COLOR_RUSSET_G 70
#define COLOR_RUSSET_B 27
#define COLOR_RUSSET_HEX COLOR_RUSSET_R << 16 | COLOR_RUSSET_G  << 8 | COLOR_RUSSET_B


#define COLOR_RUST_R 141
#define COLOR_RUST_G 64
#define COLOR_RUST_B 4
#define COLOR_RUST_HEX COLOR_RUST_R << 16 | COLOR_RUST_G  << 8 | COLOR_RUST_B


#define COLOR_SABLE_R 6
#define COLOR_SABLE_G 6
#define COLOR_SABLE_B 6
#define COLOR_SABLE_HEX COLOR_SABLE_R << 16 | COLOR_SABLE_G  << 8 | COLOR_SABLE_B


#define COLOR_SADDLEBROWN_R 139
#define COLOR_SADDLEBROWN_G 69
#define COLOR_SADDLEBROWN_B 19
#define COLOR_SADDLEBROWN_HEX COLOR_SADDLEBROWN_R << 16 | COLOR_SADDLEBROWN_G  << 8 | COLOR_SADDLEBROWN_B


#define COLOR_SAFETYYELLOW_R 238
#define COLOR_SAFETYYELLOW_G 210
#define COLOR_SAFETYYELLOW_B 2
#define COLOR_SAFETYYELLOW_HEX COLOR_SAFETYYELLOW_R << 16 | COLOR_SAFETYYELLOW_G  << 8 | COLOR_SAFETYYELLOW_B


#define COLOR_SAGE_R 141
#define COLOR_SAGE_G 181
#define COLOR_SAGE_B 131
#define COLOR_SAGE_HEX COLOR_SAGE_R << 16 | COLOR_SAGE_G  << 8 | COLOR_SAGE_B


#define COLOR_SALMON_R 250
#define COLOR_SALMON_G 128
#define COLOR_SALMON_B 114
#define COLOR_SALMON_HEX COLOR_SALMON_R << 16 | COLOR_SALMON_G  << 8 | COLOR_SALMON_B


#define COLOR_SAND_R 216
#define COLOR_SAND_G 184
#define COLOR_SAND_B 99
#define COLOR_SAND_HEX COLOR_SAND_R << 16 | COLOR_SAND_G  << 8 | COLOR_SAND_B


#define COLOR_SANDCASTLE_R 218
#define COLOR_SANDCASTLE_G 193
#define COLOR_SANDCASTLE_B 124
#define COLOR_SANDCASTLE_HEX COLOR_SANDCASTLE_R << 16 | COLOR_SANDCASTLE_G  << 8 | COLOR_SANDCASTLE_B


#define COLOR_SANDDOLLAR_R 237
#define COLOR_SANDDOLLAR_G 232
#define COLOR_SANDDOLLAR_B 186
#define COLOR_SANDDOLLAR_HEX COLOR_SANDDOLLAR_R << 16 | COLOR_SANDDOLLAR_G  << 8 | COLOR_SANDDOLLAR_B


#define COLOR_SANDSTONE_R 214
#define COLOR_SANDSTONE_G 114
#define COLOR_SANDSTONE_B 41
#define COLOR_SANDSTONE_HEX COLOR_SANDSTONE_R << 16 | COLOR_SANDSTONE_G  << 8 | COLOR_SANDSTONE_B


#define COLOR_SANDYBROWN_R 244
#define COLOR_SANDYBROWN_G 164
#define COLOR_SANDYBROWN_B 96
#define COLOR_SANDYBROWN_HEX COLOR_SANDYBROWN_R << 16 | COLOR_SANDYBROWN_G  << 8 | COLOR_SANDYBROWN_B


#define COLOR_SANGRIAPURPLE_R 77
#define COLOR_SANGRIAPURPLE_G 15
#define COLOR_SANGRIAPURPLE_B 40
#define COLOR_SANGRIAPURPLE_HEX COLOR_SANGRIAPURPLE_R << 16 | COLOR_SANGRIAPURPLE_G  << 8 | COLOR_SANGRIAPURPLE_B


#define COLOR_SANGRIARED_R 94
#define COLOR_SANGRIARED_G 25
#define COLOR_SANGRIARED_B 22
#define COLOR_SANGRIARED_HEX COLOR_SANGRIARED_R << 16 | COLOR_SANGRIARED_G  << 8 | COLOR_SANGRIARED_B


#define COLOR_SAPPHIRE_R 82
#define COLOR_SAPPHIRE_G 178
#define COLOR_SAPPHIRE_B 191
#define COLOR_SAPPHIRE_HEX COLOR_SAPPHIRE_R << 16 | COLOR_SAPPHIRE_G  << 8 | COLOR_SAPPHIRE_B


#define COLOR_SCARLET_R 144
#define COLOR_SCARLET_G 13
#define COLOR_SCARLET_B 9
#define COLOR_SCARLET_HEX COLOR_SCARLET_R << 16 | COLOR_SCARLET_G  << 8 | COLOR_SCARLET_B


#define COLOR_SCORPION_R 94
#define COLOR_SCORPION_G 94
#define COLOR_SCORPION_B 94
#define COLOR_SCORPION_HEX COLOR_SCORPION_R << 16 | COLOR_SCORPION_G  << 8 | COLOR_SCORPION_B


#define COLOR_SEAFOAM_R 61
#define COLOR_SEAFOAM_G 237
#define COLOR_SEAFOAM_B 151
#define COLOR_SEAFOAM_HEX COLOR_SEAFOAM_R << 16 | COLOR_SEAFOAM_G  << 8 | COLOR_SEAFOAM_B


#define COLOR_SEAGREEN_R 46
#define COLOR_SEAGREEN_G 139
#define COLOR_SEAGREEN_B 87
#define COLOR_SEAGREEN_HEX COLOR_SEAGREEN_R << 16 | COLOR_SEAGREEN_G  << 8 | COLOR_SEAGREEN_B


#define COLOR_SEASHELL_R 255
#define COLOR_SEASHELL_G 245
#define COLOR_SEASHELL_B 238
#define COLOR_SEASHELL_HEX COLOR_SEASHELL_R << 16 | COLOR_SEASHELL_G  << 8 | COLOR_SEASHELL_B


#define COLOR_SEAWEED_R 53
#define COLOR_SEAWEED_G 74
#define COLOR_SEAWEED_B 33
#define COLOR_SEAWEED_HEX COLOR_SEAWEED_R << 16 | COLOR_SEAWEED_G  << 8 | COLOR_SEAWEED_B


#define COLOR_SEPIA_R 227
#define COLOR_SEPIA_G 183
#define COLOR_SEPIA_B 120
#define COLOR_SEPIA_HEX COLOR_SEPIA_R << 16 | COLOR_SEPIA_G  << 8 | COLOR_SEPIA_B


#define COLOR_SHADOW_R 55
#define COLOR_SHADOW_G 55
#define COLOR_SHADOW_B 55
#define COLOR_SHADOW_HEX COLOR_SHADOW_R << 16 | COLOR_SHADOW_G  << 8 | COLOR_SHADOW_B


#define COLOR_SHAMROCK_R 3
#define COLOR_SHAMROCK_G 172
#define COLOR_SHAMROCK_B 19
#define COLOR_SHAMROCK_HEX COLOR_SHAMROCK_R << 16 | COLOR_SHAMROCK_G  << 8 | COLOR_SHAMROCK_B


#define COLOR_SHORTBREAD_R 251
#define COLOR_SHORTBREAD_G 231
#define COLOR_SHORTBREAD_B 144
#define COLOR_SHORTBREAD_HEX COLOR_SHORTBREAD_R << 16 | COLOR_SHORTBREAD_G  << 8 | COLOR_SHORTBREAD_B


#define COLOR_SHREK_R 196
#define COLOR_SHREK_G 211
#define COLOR_SHREK_B 0
#define COLOR_SHREK_HEX COLOR_SHREK_R << 16 | COLOR_SHREK_G  << 8 | COLOR_SHREK_B


#define COLOR_SIENNA_R 160
#define COLOR_SIENNA_G 82
#define COLOR_SIENNA_B 45
#define COLOR_SIENNA_HEX COLOR_SIENNA_R << 16 | COLOR_SIENNA_G  << 8 | COLOR_SIENNA_B


#define COLOR_SILVER_R 192
#define COLOR_SILVER_G 192
#define COLOR_SILVER_B 192
#define COLOR_SILVER_HEX COLOR_SILVER_R << 16 | COLOR_SILVER_G  << 8 | COLOR_SILVER_B


#define COLOR_SILVERBLUE_R 173
#define COLOR_SILVERBLUE_G 173
#define COLOR_SILVERBLUE_B 201
#define COLOR_SILVERBLUE_HEX COLOR_SILVERBLUE_R << 16 | COLOR_SILVERBLUE_G  << 8 | COLOR_SILVERBLUE_B


#define COLOR_SILVERCHALICE_R 172
#define COLOR_SILVERCHALICE_G 172
#define COLOR_SILVERCHALICE_B 172
#define COLOR_SILVERCHALICE_HEX COLOR_SILVERCHALICE_R << 16 | COLOR_SILVERCHALICE_G  << 8 | COLOR_SILVERCHALICE_B


#define COLOR_SKY_R 99
#define COLOR_SKY_G 197
#define COLOR_SKY_B 218
#define COLOR_SKY_HEX COLOR_SKY_R << 16 | COLOR_SKY_G  << 8 | COLOR_SKY_B


#define COLOR_SKYBLUE_R 135
#define COLOR_SKYBLUE_G 206
#define COLOR_SKYBLUE_B 235
#define COLOR_SKYBLUE_HEX COLOR_SKYBLUE_R << 16 | COLOR_SKYBLUE_G  << 8 | COLOR_SKYBLUE_B


#define COLOR_SLATE_R 117
#define COLOR_SLATE_G 124
#define COLOR_SLATE_B 136
#define COLOR_SLATE_HEX COLOR_SLATE_R << 16 | COLOR_SLATE_G  << 8 | COLOR_SLATE_B


#define COLOR_SLATEBLUE_R 106
#define COLOR_SLATEBLUE_G 90
#define COLOR_SLATEBLUE_B 205
#define COLOR_SLATEBLUE_HEX COLOR_SLATEBLUE_R << 16 | COLOR_SLATEBLUE_G  << 8 | COLOR_SLATEBLUE_B


#define COLOR_SLATEGRAY_R 112
#define COLOR_SLATEGRAY_G 128
#define COLOR_SLATEGRAY_B 144
#define COLOR_SLATEGRAY_HEX COLOR_SLATEGRAY_R << 16 | COLOR_SLATEGRAY_G  << 8 | COLOR_SLATEGRAY_B


#define COLOR_SMASHEDPUMPKIN_R 253
#define COLOR_SMASHEDPUMPKIN_G 103
#define COLOR_SMASHEDPUMPKIN_B 58
#define COLOR_SMASHEDPUMPKIN_HEX COLOR_SMASHEDPUMPKIN_R << 16 | COLOR_SMASHEDPUMPKIN_G  << 8 | COLOR_SMASHEDPUMPKIN_B


#define COLOR_SMOKE_R 89
#define COLOR_SMOKE_G 81
#define COLOR_SMOKE_B 94
#define COLOR_SMOKE_HEX COLOR_SMOKE_R << 16 | COLOR_SMOKE_G  << 8 | COLOR_SMOKE_B


#define COLOR_SMOKEYGRAY_R 114
#define COLOR_SMOKEYGRAY_G 110
#define COLOR_SMOKEYGRAY_B 109
#define COLOR_SMOKEYGRAY_HEX COLOR_SMOKEYGRAY_R << 16 | COLOR_SMOKEYGRAY_G  << 8 | COLOR_SMOKEYGRAY_B


#define COLOR_SMOKYBLACK_R 16
#define COLOR_SMOKYBLACK_G 12
#define COLOR_SMOKYBLACK_B 8
#define COLOR_SMOKYBLACK_HEX COLOR_SMOKYBLACK_R << 16 | COLOR_SMOKYBLACK_G  << 8 | COLOR_SMOKYBLACK_B


#define COLOR_SNOW_R 245
#define COLOR_SNOW_G 254
#define COLOR_SNOW_B 253
#define COLOR_SNOW_HEX COLOR_SNOW_R << 16 | COLOR_SNOW_G  << 8 | COLOR_SNOW_B


#define COLOR_SNOWDRIFT_R 248
#define COLOR_SNOWDRIFT_G 251
#define COLOR_SNOWDRIFT_B 248
#define COLOR_SNOWDRIFT_HEX COLOR_SNOWDRIFT_R << 16 | COLOR_SNOWDRIFT_G  << 8 | COLOR_SNOWDRIFT_B


#define COLOR_SOFTPEACH_R 246
#define COLOR_SOFTPEACH_G 241
#define COLOR_SOFTPEACH_B 244
#define COLOR_SOFTPEACH_HEX COLOR_SOFTPEACH_R << 16 | COLOR_SOFTPEACH_G  << 8 | COLOR_SOFTPEACH_B


#define COLOR_SONICGRAY_R 117
#define COLOR_SONICGRAY_G 117
#define COLOR_SONICGRAY_B 117
#define COLOR_SONICGRAY_HEX COLOR_SONICGRAY_R << 16 | COLOR_SONICGRAY_G  << 8 | COLOR_SONICGRAY_B


#define COLOR_SOOT_R 22
#define COLOR_SOOT_G 13
#define COLOR_SOOT_B 8
#define COLOR_SOOT_HEX COLOR_SOOT_R << 16 | COLOR_SOOT_G  << 8 | COLOR_SOOT_B


#define COLOR_SPACECADET_R 29
#define COLOR_SPACECADET_G 41
#define COLOR_SPACECADET_B 81
#define COLOR_SPACECADET_HEX COLOR_SPACECADET_R << 16 | COLOR_SPACECADET_G  << 8 | COLOR_SPACECADET_B


#define COLOR_SPANISHORANGE_R 240
#define COLOR_SPANISHORANGE_G 97
#define COLOR_SPANISHORANGE_B 5
#define COLOR_SPANISHORANGE_HEX COLOR_SPANISHORANGE_R << 16 | COLOR_SPANISHORANGE_G  << 8 | COLOR_SPANISHORANGE_B


#define COLOR_SPICE_R 122
#define COLOR_SPICE_G 56
#define COLOR_SPICE_B 3
#define COLOR_SPICE_HEX COLOR_SPICE_R << 16 | COLOR_SPICE_G  << 8 | COLOR_SPICE_B


#define COLOR_SPIDER_R 4
#define COLOR_SPIDER_G 2
#define COLOR_SPIDER_B 0
#define COLOR_SPIDER_HEX COLOR_SPIDER_R << 16 | COLOR_SPIDER_G  << 8 | COLOR_SPIDER_B


#define COLOR_SPRING_R 0
#define COLOR_SPRING_G 240
#define COLOR_SPRING_B 168
#define COLOR_SPRING_HEX COLOR_SPRING_R << 16 | COLOR_SPRING_G  << 8 | COLOR_SPRING_B


#define COLOR_SPRINGGREEN_R 0
#define COLOR_SPRINGGREEN_G 255
#define COLOR_SPRINGGREEN_B 127
#define COLOR_SPRINGGREEN_HEX COLOR_SPRINGGREEN_R << 16 | COLOR_SPRINGGREEN_G  << 8 | COLOR_SPRINGGREEN_B


#define COLOR_SPRUCE_R 44
#define COLOR_SPRUCE_G 62
#define COLOR_SPRUCE_B 76
#define COLOR_SPRUCE_HEX COLOR_SPRUCE_R << 16 | COLOR_SPRUCE_G  << 8 | COLOR_SPRUCE_B


#define COLOR_SQUASH_R 201
#define COLOR_SQUASH_G 91
#define COLOR_SQUASH_B 12
#define COLOR_SQUASH_HEX COLOR_SQUASH_R << 16 | COLOR_SQUASH_G  << 8 | COLOR_SQUASH_B


#define COLOR_STEELBLUE_R 70
#define COLOR_STEELBLUE_G 130
#define COLOR_STEELBLUE_B 180
#define COLOR_STEELBLUE_HEX COLOR_STEELBLUE_R << 16 | COLOR_STEELBLUE_G  << 8 | COLOR_STEELBLUE_B


#define COLOR_STONEBLUE_R 89
#define COLOR_STONEBLUE_G 120
#define COLOR_STONEBLUE_B 142
#define COLOR_STONEBLUE_HEX COLOR_STONEBLUE_R << 16 | COLOR_STONEBLUE_G  << 8 | COLOR_STONEBLUE_B


#define COLOR_STRAWBERRY_R 252
#define COLOR_STRAWBERRY_G 76
#define COLOR_STRAWBERRY_B 78
#define COLOR_STRAWBERRY_HEX COLOR_STRAWBERRY_R << 16 | COLOR_STRAWBERRY_G  << 8 | COLOR_STRAWBERRY_B


#define COLOR_STRONGMAGENTA_R 161
#define COLOR_STRONGMAGENTA_G 4
#define COLOR_STRONGMAGENTA_B 90
#define COLOR_STRONGMAGENTA_HEX COLOR_STRONGMAGENTA_R << 16 | COLOR_STRONGMAGENTA_G  << 8 | COLOR_STRONGMAGENTA_B


#define COLOR_SUCCULENT_R 168
#define COLOR_SUCCULENT_G 192
#define COLOR_SUCCULENT_B 144
#define COLOR_SUCCULENT_HEX COLOR_SUCCULENT_R << 16 | COLOR_SUCCULENT_G  << 8 | COLOR_SUCCULENT_B


#define COLOR_SUGARCOOKIE_R 243
#define COLOR_SUGARCOOKIE_G 234
#define COLOR_SUGARCOOKIE_B 175
#define COLOR_SUGARCOOKIE_HEX COLOR_SUGARCOOKIE_R << 16 | COLOR_SUGARCOOKIE_G  << 8 | COLOR_SUGARCOOKIE_B


#define COLOR_SUNFLOWER_R 255
#define COLOR_SUNFLOWER_G 218
#define COLOR_SUNFLOWER_B 3
#define COLOR_SUNFLOWER_HEX COLOR_SUNFLOWER_R << 16 | COLOR_SUNFLOWER_G  << 8 | COLOR_SUNFLOWER_B


#define COLOR_SUNSHINEYELLOW_R 255
#define COLOR_SUNSHINEYELLOW_G 253
#define COLOR_SUNSHINEYELLOW_B 55
#define COLOR_SUNSHINEYELLOW_HEX COLOR_SUNSHINEYELLOW_R << 16 | COLOR_SUNSHINEYELLOW_G  << 8 | COLOR_SUNSHINEYELLOW_B


#define COLOR_SYRUP_R 72
#define COLOR_SYRUP_G 31
#define COLOR_SYRUP_B 1
#define COLOR_SYRUP_HEX COLOR_SYRUP_R << 16 | COLOR_SYRUP_G  << 8 | COLOR_SYRUP_B


#define COLOR_TAFFY_R 250
#define COLOR_TAFFY_G 134
#define COLOR_TAFFY_B 196
#define COLOR_TAFFY_HEX COLOR_TAFFY_R << 16 | COLOR_TAFFY_G  << 8 | COLOR_TAFFY_B


#define COLOR_TAN_R 210
#define COLOR_TAN_G 180
#define COLOR_TAN_B 140
#define COLOR_TAN_HEX COLOR_TAN_R << 16 | COLOR_TAN_G  << 8 | COLOR_TAN_B


#define COLOR_TANGELO_R 252
#define COLOR_TANGELO_G 76
#define COLOR_TANGELO_B 2
#define COLOR_TANGELO_HEX COLOR_TANGELO_R << 16 | COLOR_TANGELO_G  << 8 | COLOR_TANGELO_B


#define COLOR_TANGERINE_R 250
#define COLOR_TANGERINE_G 129
#define COLOR_TANGERINE_B 40
#define COLOR_TANGERINE_HEX COLOR_TANGERINE_R << 16 | COLOR_TANGERINE_G  << 8 | COLOR_TANGERINE_B


#define COLOR_TAUPE_R 72
#define COLOR_TAUPE_G 60
#define COLOR_TAUPE_B 50
#define COLOR_TAUPE_HEX COLOR_TAUPE_R << 16 | COLOR_TAUPE_G  << 8 | COLOR_TAUPE_B


#define COLOR_TEAL_R 0
#define COLOR_TEAL_G 128
#define COLOR_TEAL_B 128
#define COLOR_TEAL_HEX COLOR_TEAL_R << 16 | COLOR_TEAL_G  << 8 | COLOR_TEAL_B


#define COLOR_THISTLE_R 216
#define COLOR_THISTLE_G 191
#define COLOR_THISTLE_B 216
#define COLOR_THISTLE_HEX COLOR_THISTLE_R << 16 | COLOR_THISTLE_G  << 8 | COLOR_THISTLE_B


#define COLOR_TIFFANYBLUE_R 129
#define COLOR_TIFFANYBLUE_G 216
#define COLOR_TIFFANYBLUE_B 208
#define COLOR_TIFFANYBLUE_HEX COLOR_TIFFANYBLUE_R << 16 | COLOR_TIFFANYBLUE_G  << 8 | COLOR_TIFFANYBLUE_B


#define COLOR_TIGER_R 252
#define COLOR_TIGER_G 106
#define COLOR_TIGER_B 3
#define COLOR_TIGER_HEX COLOR_TIGER_R << 16 | COLOR_TIGER_G  << 8 | COLOR_TIGER_B


#define COLOR_TOMATO_R 255
#define COLOR_TOMATO_G 99
#define COLOR_TOMATO_B 71
#define COLOR_TOMATO_HEX COLOR_TOMATO_R << 16 | COLOR_TOMATO_G  << 8 | COLOR_TOMATO_B


#define COLOR_TORTILLA_R 154
#define COLOR_TORTILLA_G 123
#define COLOR_TORTILLA_B 79
#define COLOR_TORTILLA_HEX COLOR_TORTILLA_R << 16 | COLOR_TORTILLA_G  << 8 | COLOR_TORTILLA_B


#define COLOR_TROPICALRAINFOREST_R 0
#define COLOR_TROPICALRAINFOREST_G 117
#define COLOR_TROPICALRAINFOREST_B 94
#define COLOR_TROPICALRAINFOREST_HEX COLOR_TROPICALRAINFOREST_R << 16 | COLOR_TROPICALRAINFOREST_G  << 8 | COLOR_TROPICALRAINFOREST_B


#define COLOR_TULIPPINK_R 255
#define COLOR_TULIPPINK_G 142
#define COLOR_TULIPPINK_B 142
#define COLOR_TULIPPINK_HEX COLOR_TULIPPINK_R << 16 | COLOR_TULIPPINK_G  << 8 | COLOR_TULIPPINK_B


#define COLOR_TURKISHBLUE_R 79
#define COLOR_TURKISHBLUE_G 151
#define COLOR_TURKISHBLUE_B 163
#define COLOR_TURKISHBLUE_HEX COLOR_TURKISHBLUE_R << 16 | COLOR_TURKISHBLUE_G  << 8 | COLOR_TURKISHBLUE_B


#define COLOR_TURQUOISE_R 64
#define COLOR_TURQUOISE_G 224
#define COLOR_TURQUOISE_B 208
#define COLOR_TURQUOISE_HEX COLOR_TURQUOISE_R << 16 | COLOR_TURQUOISE_G  << 8 | COLOR_TURQUOISE_B


#define COLOR_UMBER_R 53
#define COLOR_UMBER_G 35
#define COLOR_UMBER_B 21
#define COLOR_UMBER_HEX COLOR_UMBER_R << 16 | COLOR_UMBER_G  << 8 | COLOR_UMBER_B


#define COLOR_USAFACADEMYBLUE_R 0
#define COLOR_USAFACADEMYBLUE_G 79
#define COLOR_USAFACADEMYBLUE_B 152
#define COLOR_USAFACADEMYBLUE_HEX COLOR_USAFACADEMYBLUE_R << 16 | COLOR_USAFACADEMYBLUE_G  << 8 | COLOR_USAFACADEMYBLUE_B


#define COLOR_USFLAG_R 179
#define COLOR_USFLAG_G 25
#define COLOR_USFLAG_B 66
#define COLOR_USFLAG_HEX COLOR_USFLAG_R << 16 | COLOR_USFLAG_G  << 8 | COLOR_USFLAG_B


#define COLOR_VAMPIREBLACK_R 15
#define COLOR_VAMPIREBLACK_G 4
#define COLOR_VAMPIREBLACK_B 4
#define COLOR_VAMPIREBLACK_HEX COLOR_VAMPIREBLACK_R << 16 | COLOR_VAMPIREBLACK_G  << 8 | COLOR_VAMPIREBLACK_B


#define COLOR_VERMILION_R 126
#define COLOR_VERMILION_G 25
#define COLOR_VERMILION_B 27
#define COLOR_VERMILION_HEX COLOR_VERMILION_R << 16 | COLOR_VERMILION_G  << 8 | COLOR_VERMILION_B


#define COLOR_VERONICA_R 160
#define COLOR_VERONICA_G 32
#define COLOR_VERONICA_B 240
#define COLOR_VERONICA_HEX COLOR_VERONICA_R << 16 | COLOR_VERONICA_G  << 8 | COLOR_VERONICA_B


#define COLOR_VIOLET_R 138
#define COLOR_VIOLET_G 43
#define COLOR_VIOLET_B 226
#define COLOR_VIOLET_HEX COLOR_VIOLET_R << 16 | COLOR_VIOLET_G  << 8 | COLOR_VIOLET_B


#define COLOR_VIOLET_R 143
#define COLOR_VIOLET_G 0
#define COLOR_VIOLET_B 255
#define COLOR_VIOLET_HEX COLOR_VIOLET_R << 16 | COLOR_VIOLET_G  << 8 | COLOR_VIOLET_B


#define COLOR_VISTAWHITE_R 253
#define COLOR_VISTAWHITE_G 252
#define COLOR_VISTAWHITE_B 250
#define COLOR_VISTAWHITE_HEX COLOR_VISTAWHITE_R << 16 | COLOR_VISTAWHITE_G  << 8 | COLOR_VISTAWHITE_B


#define COLOR_VIVIDORANGE_R 255
#define COLOR_VIVIDORANGE_G 94
#define COLOR_VIVIDORANGE_B 14
#define COLOR_VIVIDORANGE_HEX COLOR_VIVIDORANGE_R << 16 | COLOR_VIVIDORANGE_G  << 8 | COLOR_VIVIDORANGE_B


#define COLOR_WALNUT_R 67
#define COLOR_WALNUT_G 38
#define COLOR_WALNUT_B 22
#define COLOR_WALNUT_HEX COLOR_WALNUT_R << 16 | COLOR_WALNUT_G  << 8 | COLOR_WALNUT_B


#define COLOR_WATERMELON_R 235
#define COLOR_WATERMELON_G 75
#define COLOR_WATERMELON_B 75
#define COLOR_WATERMELON_HEX COLOR_WATERMELON_R << 16 | COLOR_WATERMELON_G  << 8 | COLOR_WATERMELON_B


#define COLOR_WATERMELONRIND_R 92
#define COLOR_WATERMELONRIND_G 178
#define COLOR_WATERMELONRIND_B 57
#define COLOR_WATERMELONRIND_HEX COLOR_WATERMELONRIND_R << 16 | COLOR_WATERMELONRIND_G  << 8 | COLOR_WATERMELONRIND_B


#define COLOR_WHEAT_R 245
#define COLOR_WHEAT_G 222
#define COLOR_WHEAT_B 179
#define COLOR_WHEAT_HEX COLOR_WHEAT_R << 16 | COLOR_WHEAT_G  << 8 | COLOR_WHEAT_B


#define COLOR_WHITE_R 255
#define COLOR_WHITE_G 255
#define COLOR_WHITE_B 255
#define COLOR_WHITE_HEX COLOR_WHITE_R << 16 | COLOR_WHITE_G  << 8 | COLOR_WHITE_B


#define COLOR_WHITESMOKE_R 245
#define COLOR_WHITESMOKE_G 245
#define COLOR_WHITESMOKE_B 245
#define COLOR_WHITESMOKE_HEX COLOR_WHITESMOKE_R << 16 | COLOR_WHITESMOKE_G  << 8 | COLOR_WHITESMOKE_B


#define COLOR_WINE_R 78
#define COLOR_WINE_G 7
#define COLOR_WINE_B 7
#define COLOR_WINE_HEX COLOR_WINE_R << 16 | COLOR_WINE_G  << 8 | COLOR_WINE_B


#define COLOR_WOOD_R 63
#define COLOR_WOOD_G 48
#define COLOR_WOOD_B 29
#define COLOR_WOOD_HEX COLOR_WOOD_R << 16 | COLOR_WOOD_G  << 8 | COLOR_WOOD_B


#define COLOR_XANTHIC_R 238
#define COLOR_XANTHIC_G 237
#define COLOR_XANTHIC_B 9
#define COLOR_XANTHIC_HEX COLOR_XANTHIC_R << 16 | COLOR_XANTHIC_G  << 8 | COLOR_XANTHIC_B


#define COLOR_YALEBLUE_R 0
#define COLOR_YALEBLUE_G 53
#define COLOR_YALEBLUE_B 107
#define COLOR_YALEBLUE_HEX COLOR_YALEBLUE_R << 16 | COLOR_YALEBLUE_G  << 8 | COLOR_YALEBLUE_B


#define COLOR_YAM_R 204
#define COLOR_YAM_G 88
#define COLOR_YAM_B 1
#define COLOR_YAM_HEX COLOR_YAM_R << 16 | COLOR_YAM_G  << 8 | COLOR_YAM_B


#define COLOR_YELLOW_R 255
#define COLOR_YELLOW_G 255
#define COLOR_YELLOW_B 0
#define COLOR_YELLOW_HEX COLOR_YELLOW_R << 16 | COLOR_YELLOW_G  << 8 | COLOR_YELLOW_B


#define COLOR_YELLOWGREEN_R 154
#define COLOR_YELLOWGREEN_G 205
#define COLOR_YELLOWGREEN_B 50
#define COLOR_YELLOWGREEN_HEX COLOR_YELLOWGREEN_R << 16 | COLOR_YELLOWGREEN_G  << 8 | COLOR_YELLOWGREEN_B


#define COLOR_YELLOWISHGREEN_R 173
#define COLOR_YELLOWISHGREEN_G 255
#define COLOR_YELLOWISHGREEN_B 47
#define COLOR_YELLOWISHGREEN_HEX COLOR_YELLOWISHGREEN_R << 16 | COLOR_YELLOWISHGREEN_G  << 8 | COLOR_YELLOWISHGREEN_B


#define COLOR_YELLOWTAN_R 255
#define COLOR_YELLOWTAN_G 227
#define COLOR_YELLOWTAN_B 110
#define COLOR_YELLOWTAN_HEX COLOR_YELLOWTAN_R << 16 | COLOR_YELLOWTAN_G  << 8 | COLOR_YELLOWTAN_B

#endif